#include <string>
#include <unordered_map>

std::unordered_map<string, std::string> UamoidMap = {
        {"BP_GameInstance_C", "游戏实例"},
        {"BP_StartupGamemode_C", "启动游戏模式"},
        {"BP_GCloudDolphin_C", "云海豚"},
        {"BP_GCloudTGPA_C", "云TGPA"},
        {"BP_MobileHUDWidget_Login_Check_C", "移动HUD小部件 登录检查"},
        {"BP_GcloudPuffer_C", "云Puffer"},
        {"BP_NetworkMainMessageHandler_C", "网络主消息处理器"},
        {"BP_GCloudRobot_C", "云机器人"},
        {"BP_PandoraService_C", "Pandora服务"},
        {"BP_MFVoice_C", "MFVoice"},
        {"BP_MFMidas_C", "MFMidas"},
        {"BP_ShareFriend_C", "分享好友"},
        {"BP_WebView_C", "网络视图"},
        {"BP_MFTGALive_C", "MFTGALive"},
        {"BP_ClanGroup_C", "氏族团体"},
        {"BP_MNA_C", "MNA"},
        {"BP_MFBox_C", "MFBox"},
        {"BP_GCloudLogin_C", "云登录"},
        {"BP_InBattleMessage_C", "战斗消息"},
        {"BP_GCloudNetWorkState_C", "云网络状态"},
        {"BP_GCloudLoginMessageHandler_C", "云登录消息处理器"},
        {"BP_Mag_556x45mm_10R_PMAG_GEN3_Uam_C", "556x45mm弹匣 10发 PMAG GEN3 Uam"},
        {"BP_Mag_556x45mm_20R_PMAG_GEN3_Uam_C", "556x45mm弹匣 20发 PMAG GEN3 Uam"},
        {"BP_Mag_556x45mm_30R_PMAG_GEN3_Uam_C", "556x45mm弹匣 30发 PMAG GEN3 Uam"},
        {"BP_Mag_545x39mm_95R_RPK_Uam.BP_Mag_545x39mm_95R_RPK_Uam_C", "545x39mm弹匣 95发 RPK Uam"},
        {"BP_Mag_9x19mm_20R_Suomi_Uam.BP_Mag_9x19mm_20R_Suomi_Uam_C", "9x19mm弹匣 20发 Suomi Uam"},
        {"BP_Mag_9x19mm_40R_Suomi_Uam.BP_Mag_9x19mm_40R_Suomi_Uam_C", "9x19mm弹匣 40发 Suomi Uam"},
        {"BP_Muzzle_556x45mm_USGIA2_Uam.BP_Muzzle_556x45mm_USGIA2_Uam_C", "556x45mm 枪口装置 USGIA2 Uam"},
        {"BP_ChargingHandle_AR15_BOTL_C", "AR15机匣拉柄 BOTL"},
        {"BP_LoginGamemode_C", "登录游戏模式"},
        {"BP_LoginPlayerController_C", "登录玩家控制器"},
        {"BP_UamCharacterTemplate_Preview_C", "Uam角色模板 预览"},
        {"BP_CharacterFacialAnimationSets_Uam_C", "Uam角色面部动画集"},
        {"BP_CorpseContainer_C", "尸体容器"},
        {"BP_Gloves_01_C", "手套 01"},
        {"BP_Head_01_C", "头部 01"},
        {"BP_Legs_01_C", "腿部 01"},
        {"BP_Shoes_01_C", "鞋子 01"},
        {"BP_Torso_01_C", "躯干 01"},
        {"BP_CharacterAnimationSets_EmptyHand_Uam_C", "Uam角色动画集 空手"},
        {"BP_DamageType_UammptyHand_C", "Uam伤害类型 空手"},
        {"BP_PCHUDWidget_CrosshairStyle_Melee_C", "玩家控制器HUD小部件 十字准心风格 近战"},
        {"BP_AvatarBase_C", "头像基础"},
        {"BP_MobileHUDWidget_Login_C", "移动HUD小部件 登录"},
        {"BP_MobileHUDWidget_Login_Privacy_C", "移动HUD小部件 登录 隐私"},
        {"BP_MobileHUDWidget_News_01_Login_C", "移动HUD小部件 新闻 01 登录"},
        {"BP_YesNoDialog_C", "是/否对话框"},
        {"BP_RichTextLine_C", "富文本行"},
        {"BP_GCloudNotice_C", "云通知"},
        {"BP_Head_04_C", "头部 04"},
        {"BP_CharacterAnimationSets_Melee_Uam_C", "Uam角色动画集 近战"},
        {"BP_DamageType_Pan_C", "平底锅伤害类型"},
        {"BP_M9_FireModeMeleeHit_C", "M9火器模式 近战命中"},
        {"BP_MeleeWeaponBase_C", "近战武器基础"},
        {"BP_SGWeapon_C", "霰弹枪武器"},
        {"BP_Weapon_M9_Bayonet_Uam_C", "M9刺刀 武器"},
        {"BP_LoadingEntLobby_C", "加载界面 大厅"},
        {"BP_FrontEndGameMode_C", "前端游戏模式"},
        {"BP_FrontEndSceneInteractionParams_C", "前端场景交互参数"},
        {"BP_MainVideoController_C", "主视频控制器"},
        {"BP_UamCharacter_PreviewCapture_C", "Uam角色 预览捕捉"},
        {"BP_PreviewCapture_Character_LightSets_C", "预览捕捉 角色光照设置"},
        {"BP_FrontEndGameState_C", "前端游戏状态"},
        {"BP_FrontEndHUD_C", "前端HUD"},
        {"BP_FrontEndPlayerController_C", "前端玩家控制器"},
        {"BP_FrontEndPlayerState_C", "前端玩家状态"},
        {"BP_CaptureLights_FX2_Male_Rifle_C", "捕捉光效 FX2 男性 步枪"},
        {"BP_CaptureLights_FX_Male_Rifle_C", "捕捉光效 FX 男性 步枪"},
        {"BP_CaptureLights_Test_Male_Rifle_C", "捕捉光效 测试 男性 步枪"},
        {"BP_CaptureLights_YC_Female_Melee_C", "捕捉光效 YC 女性 近战"},
        {"BP_CaptureLights_YC_Female_Pistol_C", "捕捉光效 YC 女性 手枪"},
        {"BP_CaptureLights_YC_Female_Rifle_C", "捕捉光效 YC 女性 步枪"},
        {"BP_CaptureLights_YC_Male_Melee_C", "捕捉光效 YC 男性 近战"},
        {"BP_CaptureLights_YC_Male_Pistol_C", "捕捉光效 YC 男性 手枪"},
        {"BP_CaptureLights_YC_Male_Rifle_C", "捕捉光效 YC 男性 步枪"},
        {"BP_FrontEndPlayerCameraManager_C", "前端玩家摄像机管理器"},
        {"BP_CameraFocusComponent_C", "摄像机聚焦组件"},
        {"BP_Smoke4_C", "烟雾效果"},
        {"BP_MeleeAvatar_C", "近战角色模型"},
        {"BP_WeaponAssemblePreview_C", "武器预览"},
        {"BP_LobbyPlaneBGController_C", "大厅飞机背景控制器"},
        {"BP_BadgeCaptureActorSimple_C", "队徽捕获角色"},
        {"BP_CameraRatateFocusComponent_C", "摄像机旋转聚焦组件"},
        {"BP_ShowRoomBadgePreviewer_C", "展示房间徽章预览器"},
        {"BP_ShowRoomCapture_C", "展示房间捕获器"},
        {"BP_ShowRoomMeshPreviewer_C", "展示房间模型预览器"},
        {"BP_TeamPrepareMediaController_C", "团队准备媒体控制器"},
        {"BP_TeamprepareSkyLightController_C", "团队准备天光控制器"},
        {"BP_AKs74n_AnimBp_C", "AKs74n动画角色"},
        {"BP_RPK_AnimBp_C", "RPK动画角色"},
        {"BP_SVDS_AnimBp_C", "SVDS动画角色"},
        {"BP_BigMap_DossSucceed_C", "大地图完成"},
        {"BP_CharacterAnimationSets_EmptyHand_Uam_Male_C", "空手男性角色动画集"},
        {"BP_PerWeaponAnimationSets_Uam_EmptyHand_C", "每种武器动画集"},
        {"BP_PMC00_Head_01_C", "PMC00头部模型"},
        {"BP_Bag_Pocket_Default_C", "默认口袋袋子"},
        {"BP_ContainerBase_C", "容器基类"},
        {"BP_ArmoredContainerBase_C", "装甲容器基类"},
        {"BP_ChestRigs_VestContainer_M1_C", "背心式背心容器"},
        {"BP_Bag_MyContainer_Sling_C", "悬挂式背包容器"},
        {"BP_CharacterAnimationSets_Rifle_Uam_C", "步枪男性角色动画集"},
        {"BP_DamageType_MP133_Uam_C", "MP133伤害类型"},
        {"BP_MainWeaponBase_C", "主要武器基类"},
        {"BP_Shotgun_WeaponBase_C", "霰弹枪武器基类"},
        {"BP_Weapon_MP133_Uam_C", "MP133霰弹枪"},
        {"BP_Helmet_Hat_R5SL_C", "R5SL头盔帽"},
        {"BP_HelmetBase_C", "头盔基类"},
        {"BP_Package_11_C", "包裹物品"},
        {"BP_CharacterAnimationSets_Melee_Uam_Male_C", "近战男性角色动画集"},
        {"BP_M9_AnimBP_Child_C", "M9手枪动画角色"},
        {"BP_Weapon_Base_AnimBp_C", "武器基类动画角色"},
        {"BP_PerWeaponAnimationSets_Uam_M9_C", "每种武器动画集"},
        {"BP_MP133_AnimBP_Child_C", "MP133霰弹枪动画角色"},
        {"BP_CharacterAnimationSets_Rifle_Uam_Male_C", "步枪男性角色动画集"},
        {"BP_PerWeaponAnimationSets_Uam_MP133_C", "每种武器动画集"},
        {"BP_Barrel_MP133_660mm_Uam_C", "MP133枪管"},
        {"BP_BarrelBase_C", "枪管基类"},
        {"BP_HandGuard_MP133_custom_Uam_C", "MP133自定义手把"},
        {"BP_HandGuardBase_C", "手把基类"},
        {"BP_Stock_MP133_plastic_Uam_C", "MP133塑料枪托"},
        {"BP_StockBase_C", "枪托基类"},
        {"BP_12x70_7mm_Buckshot_Uam_C", "12x70 7mm火铳弹"},
        {"BP_Caliber_12x70_Uam_C", "12x70口径"},
        {"BP_Mag_12x70mm_6R_mp133_Uam_C", "12x70mm 6发弹匣"},
        {"BP_MagazineBase_C", "弹夹基类"},
        {"BP_AmmoBase_C", "弹药基类"},
        {"BP_MobileWidget_Deploy_All1_C", "部署所有界面组件"},
        {"BP_MobileWidget_Deploy_Mentor_C", "部署导师界面"},
        {"BP_MobileWidget_PlayerInfo_C", "玩家信息界面"},
        {"BP_MobileWidget__Title_C", "标题界面"},
        {"BP_MobileWidget_PlayerAvatarIcon_C", "玩家头像图标界面"},
        {"BP_MobileWidget_PrivilegeIcon_C", "特权图标界面"},
        {"BP_SceneRenderingSettings_C", "场景渲染设置"},
        {"BP_GraphicStylesOverridePPVs_C", "图形样式覆盖后处理体积"},
        {"BP_MFClimateCirrusComponent_C", "MF Cirrus组件"},
        {"BP_MFClimateMobileLightningDirector_C", "MF移动闪电导演"},
        {"BP_MFClimateOnePassSky_C", "MF单通道天空"},
        {"BP_MFClimateSunMoonSceneLightComponent_C", "MF太阳月亮场景光组件"},
        {"BP_NewMFClimate_C", "新的MF气候"},
        {"BP_UAGlobalCloudMask_C", "UA全球云遮罩"},
        {"BP_UAMFClimateSky_C", "UA MF天空"},
        {"BP_UAMoon_C", "UA月亮"},
        {"BP_UARain_C", "UA雨"},
        {"BP_UASun_C", "UA太阳"},
        {"BP_LootAreaVolume_C", "战利品区域体积"},
        {"BP_UAWeatherMapGenerator_C", "UA天气地图生成器"},
        {"BP_UAWeatherMixer_C", "UA天气混合器"},
        {"BP_WeatherMapGenerator_C", "天气地图生成器"},
        {"BP_LootSubAreaVolume_C", "战利品子区域体积"},
        {"BP_MissionInteractVolume_C", "任务交互体积"},
        {"BP_MissionItemSpawnPoint_C", "任务物品生成点"},
        {"BP_MobileWidget_ItemInteraction_C", "物品交互界面"},
        {"BP_PylonPoint_2_C", "电塔点"},
        {"BP_QuestAreaVolume_C", "任务区域体积"},
        {"BP_QuestItemSpawnPoint_C", "任务物品生成点"},
        {"BP_QuestVolume_C", "任务区域体积"},
        {"BP_UamGashaponSpawnPoint_C", "UAM扭蛋机生成点"},
        {"BP_ParadropPoint_C", "空投点"},
        {"BP_EffectActor_C", "效果角色"},
        {"BP_ShowControlActorNew_C", "展示控制角色新"},
        {"BP_UamEscapeInteractVolume_C", "UA逃生交互体积"},
        {"BP_UamEscapeTimerGlobalComponent_C", "UA逃生计时器全局组件"},
        {"BP_UamEscapeVolume_New_C", "UA逃生区域新"},
        {"BP_UamPlayerStart_C", "UA玩家起始点"},
        {"BP_AIEscapeController_C", "AI逃生控制器"},
        {"BP_MobileHUDWidget_EscapeInteract_New_C", "移动HUD界面逃生交互新"},
        {"BP_SoundSwitcher_C", "声音切换器"},
        {"BP_Bulb_C", "灯泡"},
        {"BP_Crickent_C", "蟋蟀"},
        {"BP_DeathBoxScav2_C", "死亡箱子(拾取模式)"},
        {"BP_DeathBoxScav_C", "死亡箱子(拾取模式)"},
        {"BP_Ibuprofen_C", "布洛芬"},
        {"BP_IFAK_C", "急救包"},
        {"BP_Intelligence_C", "情报"},
        {"BP_NPCProfile_Cpt_Normal_Tutorial_C", "普通教程NPC角色"},
        {"BP_PainKillers_C", "止痛药"},
        {"BP_Quest_Tutorial_Bag_C", "教程背包"},
        {"BP_Quest_Tutorial_BigMap_C", "教程大地图"},
        {"BP_Quest_Tutorial_ClickItem_C", "教程点击物品"},
        {"BP_Quest_Tutorial_KillAI_C", "教程击杀AI"},
        {"BP_Quest_Tutorial_MoveItem_C", "教程移动物品"},
        {"BP_Quest_Tutorial_MoveTo_C", "教程移动到"},
        {"BP_Quest_Tutorial_UseItem_C", "教程使用物品"},
        {"BP_Request_Custom_Battle_C", "请求：自定义对战"},
        {"BP_Request_Custom_FindTargetAndFight_C", "请求：自定义寻找目标并战斗"},
        {"BP_Request_Custom_FollowTarget_C", "请求：自定义跟随目标"},
        {"BP_Request_Custom_MoveToWith_C", "请求：自定义携带"},
        {"BP_Request_Custom_RemindItemToPlayer_C", "请求：自定义提醒玩家拾取物品"},
        {"BP_Request_Custom_SuppressShoot_C", "请求：自定义压制射击"},
        {"BP_Request_Custom_TakeMedicine_C", "请求：自定义服用药物"},
        {"BP_Request_Custom_WaitForPlayerLoot_C", "请求：自定义等待玩家拾取物品"},
        {"BP_RewardBox_C", "奖励箱子"},
        {"BP_SGAISpawnPoint_C", "特种部队AI生成点"},
        {"BP_Tape_White_C", "白色胶带"},
        {"BP_ToiletPape_C", "卫生纸"},
        {"BP_Toothpaste_C", "牙膏"},
        {"BP_Tutorial_AICharacterTemplate_C", "教程AI角色模板"},
        {"BP_TutorialLootVolume_C", "教程战利品区域体积"},
        {"BP_TutorialMoveCheckVolume_C", "教程移动检查区域体积"},
        {"BP_Tutorials_Coach_C", "教程教练角色"},
        {"BP_Tutorials_PMC_2_C", "教程PMC角色(2)"},
        {"BP_Tutorials_PMC_B2_End1_C", "教程PMC角色B2(结束1)"},
        {"BP_Tutorials_PMC_B2_End2_C", "教程PMC角色B2(结束2)"},
        {"BP_Tutorials_PMC_B2RichMan_C", "教程PMC角色B2(有钱人)"},
        {"BP_UamCheckPoint_C", "UA检查点"},
        {"BP_UamCheckPointInfo_C", "UA检查点信息"},
        {"BP_UamScavAISpawnPoint_C", "逃生AI生成点"},
        {"BP_UamTutorialChoosePlayerStartComp_C", "UA教程选择玩家起始点组件"},
        {"BP_UamTutorialGameMode_C", "UA教程游戏模式"},
        {"BP_UamTutorialHelper_C", "UA教程助手"},
        {"BP_UamTutorialPlayerController_C", "UA教程玩家控制器"},
        {"BP_Wires_C", "电线"},
        {"BP_Wrench_C", "扳手"},
        {"BP_545x39mm_PS_Uam_C", "545x39mm PS子弹"},
        {"BP_9x19mm_PSO_gzh_Uam_C", "9x19mm PSO gzh子弹"},
        {"BP_AK_6p1sb8_Uam_C", "AK-74M枪型"},
        {"BP_Bag_MyContainer_MBSS_C", "我的容器(MBSS背包)"},
        {"BP_Bag_VestContainer_D3CRX_C", "背包背心容器 D3CRX"},
        {"BP_Bag_VestContainer_ScavVest_C", "背包背心容器 ScavVest"},
        {"BP_Barrel_Glock17_Threaded_Uam_C", "桶 Glock17 螺纹 Uam"},
        {"BP_ChargingHandle_AKM_Uam_C", "充气手柄 AKM Uam"},
        {"BP_GasTube_AK74_Uam_C", "燃气管 AK74 Uam"},
        {"BP_HandGuard_AK_6P20Sb9_Uam_C", "手把 AK 6P20Sb9 Uam"},
        {"BP_Helmet_LZSh_C", "头盔 LZSh"},
        {"BP_Helmet_LZSh_Default_C", "默认 LZSh 头盔"},
        {"BP_IronSight_Front_Glock17_Uam_C", "Glock17 前瞄准器"},
        {"BP_IronSight_Rear_AK_Uam_C", "AK 后瞄准器"},
        {"BP_IronSight_Rear_Glock17_Uam_C", "Glock17 后瞄准器"},
        {"BP_LZ_C", "LZ"},
        {"BP_Mag_545x39mm_30R_6L20_Uam_C", "545x39mm 30发弹匣 6L20 Uam"},
        {"BP_Mag_9x19mm_17R_Glock17_Uam_C", "9x19mm 17发弹匣 Glock17 Uam"},
        {"BP_Matches_C", "火柴"},
        {"BP_MedicalScissors_C", "医用剪刀"},
        {"BP_MedicalSponge_C", "医用海绵"},
        {"BP_Muzzle_545x39mm_6P20_020_Uam_C", "545x39mm 6P20 020 枪口"},
        {"BP_NaCl_C", "氯化钠"},
        {"BP_Quest_Tutorial_001_C", "教程任务 001"},
        {"BP_Quest_Tutorial_BagTab_C", "教程任务 背包选项卡"},
        {"BP_ReceiverCover_AKM_Uam_C", "AKM 接收器盖"},
        {"BP_ReceiverCover_Glock17_Standard_Uam_C", "Glock17 标准接收器盖"},
        {"BP_Sight_ReflexSight_EKP818_Uam_C", "EKP818 反射式瞄准镜"},
        {"BP_SightBase_TT10000_C", "TT10000 瞄准器底座"},
        {"BP_Stock_AKM_VPO136_C", "AKM VPO136 枪托"},
        {"BP_Sweetener_C", "甜味剂"},
        {"BP_Syringe_C", "注射器"},
        {"BP_Tutorials_B1_1_C", "教程 B1 1"},
        {"BP_Vest_Kirasa_C", "Kirasa 背心"},
        {"BP_Weapon_AK74N_Uam_C", "AK74N 武器"},
        {"BP_Weapon_Glock17_Uam_C", "Glock17 武器"},
        {"BP_UamPmcPathPoint_C", "PMC 路径点"},
        {"BP_Quest_Greenhand_BigMap_C", "教程任务 绿手大地图"},
        {"BP_ActorEnduranceComp_C", "耐力组件"},
        {"BP_PoisonGasBase_C", "毒气基础"},
        {"BP_TwoWayDoorPlankComponent_C", "双向门木板组件"},
        {"BP_WoodenDoor_C", "木制门"},
        {"BP_Farmland_Water6_C", "远程水6"},
        {"BP_IronDoor_C", "铁门"},
        {"BP_IronDoor_Refrigerator_C", "铁门 冰箱"},
        {"BP_Env_WindMill02_Rotate_C", "风车02 旋转"},
        {"BP_Farmland_Water14_C", "远程水14"},
        {"BP_Farmland_Water7_C", "远程水7"},
        {"BP_Farmland_Water10_C", "远程水10"},
        {"BP_Farmland_Water1_C", "远程水1"},
        {"BP_Farmland_Water2_C", "远程水2"},
        {"BP_Farmland_Water3_C", "远程水3"},
        {"BP_Farmland_Water4_C", "远程水4"},
        {"BP_Farmland_Water5_C", "远程水5"},
        {"BP_Farmland_Water9_C", "远程水9"},
        {"BP_CharacterCaptureActor_C", "角色捕获演员"},
        {"BP_HUDBase_C", "HUD 基础"},
        {"BP_PlayerControllerBase_C", "玩家控制器基础"},
        {"BP_PoisonGas_Uam_C", "毒气 Uam"},
        {"BP_UamPlayerController_C", "Uam 玩家控制器"},
        {"BP_Gloves_00_C", "手套 00"},
        {"BP_head_03_C", "头部 03"},
        {"BP_Legs_06_C", "腿部 06"},
        {"BP_PFX_SmokeGrenade_C", "烟雾弹 PFX"},
        {"BP_ProjectileTrajectory_C", "弹道轨迹"},
        {"BP_SGPooledImpactEffectManager_C", "SG 固定撞击效果管理器"},
        {"BP_Shoes_06_C", "鞋子 06"},
        {"BP_SoundIndicator_C", "声音指示器"},
        {"BP_Torso_06_C", "躯干 06"},
        {"BP_UamPlayerCameraManagerTemplate_C", "Uam 玩家摄像头管理器模板"},
        {"BP_UamEscapeNewInteractVolume_C", "新互动体积"},
        {"BP_ShowControlActor_C", "显示控制演员"},
        {"BP_BaseAIController_C", "AI 控制器基础"},
        {"BP_HUD_Debug_Mobile_C", "移动版 HUD 调试"},
        {"BP_BRPlayerStart_C", "BR 玩家起始点"},
        {"BP_SE_BR_ShowEscapeVolume_C", "SE BR 显示逃生体积"},
        {"BP_CameraDebugComponent_C", "摄像头调试组件"},
        {"BP_CameraFOV_ADS_C", "ADS 摄像头视野"},
        {"BP_CameraFOV_Default_C", "默认摄像头视野"},
        {"BP_CameraShake_TakeHit_C", "受击摄像机抖动"},
        {"BP_CSEntry_LandHeavy_C", "重型登陆 CS 入口"},
        {"BP_CSEntry_LandLight_C", "轻型登陆 CS 入口"},
        {"BP_UamCameraShake_LegBoneBreak_C", "腿骨折摄像头抖动"},
        {"BP_UamCameraStyle_FirstPerson_C", "站立第一人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_Crouch_C", "蹲下第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_CrouchRun_C", "蹲下奔跑第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_CrouchSprint_C", "蹲下冲刺第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_Death_C", "死亡第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_Prone_C", "趴下第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_StandRun_C", "站立奔跑第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_StandSprint_C", "站立冲刺第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_TargetingCrouch_C", "瞄准蹲下第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_TargetingCrouchWalk_C", "瞄准蹲下行走第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_TargetingProne_C", "瞄准趴下第三人称摄像模式"},
        {"BP_UamThirdPersonCameraMode_TargetingStand_C", "瞄准站立第三人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_ClimbLadder_C", "攀爬梯子第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_Crouch_C", "蹲下第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_DBNO_C", "DBNO 第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_Default_C", "默认第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_FreeView_C", "自由视图第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_Prone_C", "趴下第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_ProneZooming_C", "趴下放大第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_Rescuer_C", "救援者第一人称摄像模式"},
        {"BP_UamFirstPersonCameraMode_Zooming_C", "放大第一人称摄像模式"},
        {"BP_CS_LandLight_C", "轻型登陆 CS 入口"},
        {"BP_HUD_HeadSubgroupPanel_C", "HUD 头部子组面板"},
        {"BP_CharacterAIHealthAttributeSet_Uam_C", "角色 AI 健康属性集 Uam"},
        {"BP_CharacterDeathAnimationSets_Uam_C", "角色死亡动画集 Uam"},
        {"BP_CharacterEnduranceAttributeSet_Uam_C", "角色耐力属性集 Uam"},
        {"BP_Dogtag2_C", "狗牌2"},
        {"BP_Dogtag_C", "狗牌"},
        {"BP_AIGroupInfo_Base_C", "AI 群组信息基础"},
        {"BP_BaseDynamicGroupInfo_C", "基础动态群组信息"},
        {"BP_DynamicGroupInfo_DossContract_C", "动态群组信息 Doss 合同"},
        {"BP_DynamicGroupInfo_Normal_C", "普通动态群组信息"},
        {"BP_DynamicGroupInfo_ProtectBoss_C", "保护首领动态群组信息"},
        {"BP_DynamicGroupInfo_SuppressionFire_C", "压制射击动态群组信息"},
        {"BP_ShowControlActor_CitySiege_Alarm_C", "城市围攻警报控制演员"},
        {"BP_ShowControlActor_CitySiege_CallHelp_C", "城市围攻呼叫援助控制演员"},
        {"BP_ShowControlActor_CitySiege_Death_C", "城市围攻死亡控制演员"},
        {"BP_ShowControlActor_CitySiege_Fight_C", "城市围攻战斗控制演员"},
        {"BP_UamAICharacter_C", "Uam AI 角色"},
        {"BP_UamAIPathNode_C", "Uam AI 路径节点"},
        {"BP_MapEffectsSwitch_C", "地图效果开关"},
        {"BP_RookieGuideEffect_C", "新手指南效果"},
        {"BP_AIBattle_SpawnVolume_C", "AI 战斗生成体积"},
        {"BP_ActorRadiusCheckComp_C", "演员半径检测组件"},
        {"BP_GasGateInteractActor_C", "毒气门互动演员"},
        {"BP_CharacterEnduranceAttributeSet_Uam_Coach_C", "角色耐力属性集 Uam 教练"},
        {"BP_CharacterFacialAnimationSets_Coach_C", "角色面部动画集 教练"},
        {"BP_Headsets_TacticalSport_C", "战术运动耳机"},
        {"BP_InstructorCoach_Gloves_C", "教练手套"},
        {"BP_InstructorCoach_Hair_C", "教练发型"},
        {"BP_InstructorCoach_Head_C", "教练头部"},
        {"BP_InstructorCoach_Leg_C", "教练腿部"},
        {"BP_InstructorCoach_Shoes_C", "教练鞋子"},
        {"BP_InstructorCoach_Torso_C", "教练躯干"},
        {"BP_InstructorCoach_Vest_C", "教练背心"},
        {"BP_Weapon_AKM_Coach_C", "AKM 武器 教练"},
        {"BP_CharacterEnergyAttributeSet_C", "角色能量属性集"},
        {"BP_CharacterFoodAttributeSet_Uam_C", "角色食物属性集 Uam"},
        {"BP_CharacterHealthAttributeSet_Uam_C", "角色健康属性集 Uam"},
        {"BP_CharacterMoistureAttributeSet_Uam_C", "角色水分属性集 Uam"},
        {"BP_CharacterMovementAttibuteSet_C", "角色移动属性集"},
        {"BP_CharacterWeightAttributeSet_C", "角色负重属性集"},
        {"BP_ThirdPersonCameraMode_Crouch_C", "蹲下第三人称摄像模式"},
        {"BP_ThirdPersonCameraMode_Stand_C", "站立第三人称摄像模式"},
        {"BP_DeathBoxScav3_C", "死亡盒子 Scav3"},
        {"BP_HeadsetsBase_C", "头戴式耳机基础"},
        {"BP_AssultRifle_WeaponBase_C", "突击步枪武器基础"},
        {"BP_CoachAnimationSets_C", "教练动画集"},
        {"BP_GasTube_AKM_Uam_C", "AKM 武器气管 Uam"},
        {"BP_HandGuard_AKM_B_10M_Uam_C", "AKM 武器护手 Uam"},
        {"BP_IronSight_Rear_AKM_Uam_C", "AKM 武器后瞄具 Uam"},
        {"BP_Pistolgrip_6P4_AKM_Uam_C", "AKM 武器握把 Uam"},
        {"BP_ReceiverCover_AKM_PDC_Uam_C", "AKM 武器弹匣 Uam"},
        {"BP_Sight_ReflexSight_MRS_Uam_C", "AKM 武器瞄准具 Uam"},
        {"BP_Stock_AKM_Wood_Uam_C", "AKM 武器枪托 Uam"},
        {"BP_Weapon_AKM_Uam_C", "AKM 武器 Uam"},
        {"BP_ItemBase_C", "物品基础"},
        {"BP_PreviewActor_C", "预览演员"},
        {"BP_BigMapAreaManagerComponent_C", "大地图区域管理器组件"},
        {"BP_UamGameState_C", "Uam 游戏状态"},
        {"BP_MultiFuncAISpawnPoint_C", "多功能 AI 生成点"},
        {"BP_Scav_AKM_C", "Scav AKM"},
        {"BP_MobileHUDWidget_DoorGateInteract_C", "移动 HUD 小部件 门闸互动"},
        {"BP_SceneGasBase_C", "场景毒气基础"},
        {"BP_LookPoint_C", "注视点"},
        {"BP_DamageType_AKM_Uam_C", "AKM 武器伤害类型 Uam"},
        {"BP_SightBase_C", "瞄准具基础"},
        {"BP_ReceiverCoverBase_C", "武器弹匣盖基础"},
        {"BP_PistolgripBase_C", "武器握把基础"},
        {"BP_Caliber_545x39mm_Uam_C", "子弹口径 5.45x39mm Uam"},
        {"BP_GasBlockBase_C", "气体阻塞器基础"},
        {"BP_ChargingHandleBase_C", "拉柄基础"},
        {"BP_RandomEquipmentAI_Template_C", "随机装备 AI 模板"},
        {"BP_GameStateBase_C", "游戏状态基础"},
        {"BP_UamFaction_C", "Uam 阵营"},
        {"BP_QuestManagerActor_C", "任务管理器演员"},
        {"BP_UamTeamInfo_C", "Uam 队伍信息"},
        {"BP_DummyQuest_C", "虚拟任务"},
        {"BP_AIGroupInfo_C", "AI 队伍信息"},
        {"BP_Trigger_X-5_C", "触发器 X-5"},
        {"BP_ProtectSafeBoxPoint_C", "保护保险箱点"},
        {"BP_Order_MoveToLoc_C", "移动到位置命令"},
        {"BP_Order_StayInLoc_C", "停留在位置命令"},
        {"BP_DynamicGroupInfo_RushFace_C", "突击面部动态组信息"},
        {"BP_DeathBoxPMC_C", "PMC 死亡盒子"},
        {"BP_TacticPoint_M18A1_C", "M18A1 战术点"},
        {"BP_SE_CallHelp_C", "呼救触发器"},
        {"BP_LootBoxBase_C", "战利品箱基础"},
        {"BP_TacticPoint_C", "战术点"},
        {"BP_Throwable_Projectile_Claymore_C", "投掷物基础"},
        {"BP_Request_Custom_C", "自定义请求"},
        {"BP_Request_Custom_ActiveAlarmDevice_C", "自定义请求 激活警报设备"},
        {"BP_Throwable_Projectile_Base_C", "投掷物基础"},
        {"BP_Quest_C", "任务"},
        {"BP_Quest_RushFace_C", "突击面部任务"},
        {"BP_NPC_DynamicGroupInfo_C", "NPC 动态组信息"},
        {"BP_Request_Custom_GrenadeToPeek_C", "自定义请求 投掷手雷窥视"},
        {"BP_Request_Custom_RushFace_C", "自定义请求 突击面部"},
        {"BP_Smoke_C", "烟雾弹"},
        {"BP_ArmorInformation_C", "护甲信息"},
        {"BP_AttributeInformation_C", "属性信息"},
        {"BP_ChafingDish_Eat_C", "加热式蒸饭器 吃"},
        {"BP_ChafingDish_Put_C", "加热式蒸饭器 放置"},
        {"BP_FirearmsRepair_C", "火器维修"},
        {"BP_GachaMachineState_C", "扭蛋机状态"},
        {"BP_GamePadView_ADS_C", "游戏手柄视图 ADS"},
        {"BP_GamePadView_Bag_C", "游戏手柄视图 背包"},
        {"BP_GamePadView_Battery_C", "游戏手柄视图 电池"},
        {"BP_GamePadView_ClimbLadder_C", "游戏手柄视图 攀爬梯子"},
        {"BP_GamePadView_Collimator_C", "游戏手柄视图 瞄准镜"},
        {"BP_GamePadView_CountDown_C", "游戏手柄视图 倒计时"},
        {"BP_GamePadView_Crouch_C", "游戏手柄视图 蹲伏"},
        {"BP_GamePadView_DBNOHealth_C", "游戏手柄视图 DBNO 健康"},
        {"BP_GamePadView_EnergyProgress_C", "游戏手柄视图 能量进度"},
        {"BP_GamePadView_Fire_C", "游戏手柄视图 射击"},
        {"BP_GamePadView_FreeView_C", "游戏手柄视图 自由视角"},
        {"BP_GamePadView_GameSetting_C", "游戏手柄视图 游戏设置"},
        {"BP_GamePadView_HoldBreath_C", "游戏手柄视图 屏息"},
        {"BP_GamePadView_HoldGrenade_C", "游戏手柄视图 握住手雷"},
        {"BP_GamePadView_Jump_C", "游戏手柄视图 跳跃"},
        {"BP_GamePadView_LaserSwitch_C", "游戏手柄视图 激光开关"},
        {"BP_GamePadView_LeanL_C", "游戏手柄视图 左倾"},
        {"BP_GamePadView_LeanR_C", "游戏手柄视图 右倾"},
        {"BP_GamePadView_LeftFire_C", "游戏手柄视图 左键射击"},
        {"BP_GamePadView_LockMove_C", "游戏手柄视图 锁定移动"},
        {"BP_GamePadView_Magnitude_C", "游戏手柄视图 幅度"},
        {"BP_GamePadView_Movement_C", "游戏手柄视图 移动"},
        {"BP_GamePadView_Prone_C", "游戏手柄视图 俯卧"},
        {"BP_GamePadView_QuickUseItem_C", "游戏手柄视图 快速使用物品"},
        {"BP_GamePadView_RescueInteraction_C", "游戏手柄视图 营救互动"},
        {"BP_GamePadView_Signal_C", "游戏手柄视图 信号"},
        {"BP_GamePadView_ThermalSwitch_C", "游戏手柄视图 热成像开关"},
        {"BP_MainHud_BigMap_C", "主界面大地图"},
        {"BP_MainHud_ChangeClip_C", "主界面更换弹匣"},
        {"BP_MainHud_Communication_C", "主界面通讯"},
        {"BP_MainHud_Mute_C", "主界面静音"},
        {"BP_MainHud_OpenBox_C", "主界面开箱"},
        {"BP_MainHud_SelectGrenade_C", "主界面选择手雷"},
        {"BP_MainHud_TostTips_C", "主界面吐司提示"},
        {"BP_MainHud_TxtTips_C", "主界面文本提示"},
        {"BP_MainHud_ViewWeapon_C", "主界面查看武器"},
        {"BP_MainHud_WeaponCheck_New_C", "主界面武器检查 新的"},
        {"BP_MainHud_WeaponSlotAssisMelee_C", "主界面武器槽 辅助 近战"},
        {"BP_MainHud_WeaponSlotMain_First_C", "主界面武器槽 主武器 一号"},
        {"BP_MainHud_WeaponSlotMain_Second_C", "主界面武器槽 主武器 二号"},
        {"BP_MobileHUDWidget_CustomInteractContainer_C", "移动 HUD 小部件 自定义互动容器"},
        {"BP_MobileHUDWidget_LifeState_C", "移动 HUD 小部件 生命状态"},
        {"BP_MobileHUDWidget_UseProgress_C", "移动 HUD 小部件 使用进度"},
        {"BP_MobileHUDWidget_WatchBattle_C", "移动 HUD 小部件 观战战斗"},
        {"BP_MobileWidget_DoorInteraction_C", "移动小部件 门互动"},
        {"BP_MobileWidget_DoorInteractionTips_C", "移动小部件 门互动提示"},
        {"BP_MobileWidget_GetInventory_C", "移动小部件 获取背包物品"},
        {"BP_MobileWidget_LootInventory_C", "移动小部件 背包物品列表"},
        {"BP_PCHUDWidget_DirectionalBar_C", "玩家控制器 HUD 小部件 方向条"},
        {"BP_SelfSoundIndicator_C", "自身声音指示器"},
        {"BP_Weapon_CancelGrenades_C", "武器 取消手雷"},
        {"BP_VerticalMenu_C", "垂直菜单"},
        {"BP_GamePadView_FireButton_Hat_C", "游戏手柄视图 开火按钮 帽子"},
        {"BP_HUDWidget_DirectionalBarSignItem_C", "HUD 小部件 方向条标志物品"},
        {"BP_MobileWidget_PickUpInventoryInfo_C", "移动小部件 获取背包信息"},
        {"BP_MobileHUDWidget_WatchBattlePlayer_C", "移动 HUD 小部件 观战玩家"},
        {"BP_MobileHUDWidget_WatchBattlePlayerItem_C", "移动 HUD 小部件 观战玩家物品"},
        {"BP_MobileHUDWidget_WatchFriendsHurt_C", "移动 HUD 小部件 观战好友受伤"},
        {"BP_MobileHUDWidget_BuffInfoDetail_C", "移动 HUD 小部件 增益信息详细"},
        {"BP_MainHud_WeaponDetail_MainSecond_C", "主界面武器详情 主武器 二号"},
        {"BP_MainHud_WeaponDetail_MainFirst_C", "主界面武器详情 主武器 一号"},
        {"BP_MainHud_WeaponDetail_Assis_C", "主界面武器详情 辅助武器"},
        {"BP_MainHud_WeaponDetail_Melee_C", "主界面武器详情 近战武器"},
        {"BP_MainHud_Grenade_C", "主界面手雷"},
        {"BP_MainHud_CommunicationLongpress_C", "主界面通讯长按"},
        {"BP_MainHud_Gesture_C", "主界面手势"},
        {"BP_MainHud_SaveText_C", "主界面保存文本"},
        {"BP_GamePadView_QuickUseItem_VFX_C", "游戏手柄视图 快速使用物品 VFX"},
        {"BP_MainHud_Change_Medicine_C", "主界面更换药品"},
        {"BP_MainHud_DragClose_C", "主界面拖拽关闭"},
        {"BP_GamePadView_FireButton_Hat_Fire_C", "游戏手柄视图 开火按钮 帽子 开火"},
        {"BP_MainHUD_Freeview_Circle_C", "主界面自由视角圆圈"},
        {"BP_GachaMachine_Tips_C", "扭蛋机提示"},
        {"BP_DirectionalBarNode_Activity_C", "方向条节点 活动"},
        {"BP_DirectionalBarNode_Common_C", "方向条节点 通用"},
        {"BP_DirectionalBarNode_Evacuation_C", "方向条节点 撤离"},
        {"BP_DirectionalBarNode_OpenBox_C", "方向条节点 开箱"},
        {"BP_DirectionalBarNode_Task_C", "方向条节点 任务"},
        {"BP_MobileWidget_Layout_PickUpInventoryBack_C", "移动小部件 布局 获取背包物品 返回"},
        {"BP_MobileWidget_PickUpInventoryIcon_C", "移动小部件 获取背包物品图标"},
        {"BP_MobileWidget_PickUpSpace_C", "移动小部件 获取背包空间"},
        {"BP_MobileHUDWidget_WatchBattlePlayerBg_C", "移动 HUD 小部件 观战玩家背景"},
        {"BP_AmmoCount_C", "弹药数量"},
        {"BP_MainHud_GrenadeItem_C", "主界面手雷物品"},
        {"BP_MainHud_Medicine_C", "主界面药品"},
        {"BP_MobileWidget_PickUpSpaceItem_C", "移动小部件 获取背包物品空间"},
        {"BP_MobileWidget_PickUpInventoryInfoGrade_C", "移动小部件 获取背包物品信息等级"},
        {"BP_MobileWidget_FX_WhiltBlink_C", "移动小部件 FX 白闪"},
        {"BP_PlayerStateBase_C", "玩家状态基类"},
        {"BP_UamPlayerState_C", "游戏玩家状态"},
        {"BP_ReplayObserverPawn_C", "重播观察者棋子"},
        {"BP_SGGameMode_C", "游戏模式基类"},
        {"BP_UamGameMode_C", "游戏模式"},
        {"BP_UamReplayController_V2_C", "游戏重播控制器 V2"},
        {"BP_UamHUD_KillCam_C", "HUD 杀戮视角"},
        {"BP_UamReplayController_C", "重播控制器"},
        {"BP_MobileWidget_Reconnect_Panel_C", "移动小部件 重连面板"},
        {"BP_762x39mm_HP_Uam_C", ".762x39mm HP"},
        {"BP_Caliber_762x39mm_Uam_C", "弹药口径 .762x39mm"},
        {"BP_762x39mm_US_Uam_C", ".762x39mm US"},
        {"BP_762x39mm_PS_Uam_C", ".762x39mm PS"},
        {"BP_762x39mm_BP_Uam_C", ".762x39mm BP"},
        {"BP_762x39mm_T45M_Uam_C", ".762x39mm T45M"},
        {"BP_762x39mm_LRNPC_C", ".762x39mm LRNPC"},
        {"BP_762x39mm_MAI_AP_C", ".762x39mm MAI AP"},
        {"BP_762x54mmR_LPS_Gzh_Uam_C", ".762x54mmR LPS Gzh"},
        {"BP_Caliber_762x54mmR_Uam_C", "弹药口径 .762x54mmR"},
        {"BP_762x54mmR_7BT1_Uam_C", ".762x54mmR 7BT1"},
        {"BP_762x54mmR_7N37_Uam_C", ".762x54mmR 7N37"},
        {"BP_762x54mmR_T46M_Uam_C", ".762x54mmR T46M"},
        {"BP_762x54mmR_SNB_Uam_C", ".762x54mmR SNB"},
        {"BP_762x54mmR_Tutorial_C", ".762x54mmR Tutorial"},
        {"BP_556x45mm_55_HP_Uam_C", ".556x45mm 55 HP"},
        {"BP_Caliber_556x45mm_Uam_C", "弹药口径 .556x45mm"},
        {"BP_556x45mm_55_FMJ_Uam_C", ".556x45mm 55 FMJ"},
        {"BP_556x45mm_M855_Uam_C", ".556x45mm M855"},
        {"BP_556x45mm_M995_Uam_C", ".556x45mm M995"},
        {"BP_556x45mm_M855A1_Uam_C", ".556x45mm M855A1"},
        {"BP_556x45mm_WG_C", ".556x45mm WG"},
        {"BP_Caliber_9x19mm_Uam_C", "弹药口径 .9x19mm"},
        {"BP_9x19mm_Pst_gzh_Uam_C", ".9x19mm Pst gzh"},
        {"BP_12x70_RIP_Uam_C", ".12x70 RIP"},
        {"BP_12x70_Led_slug_Uam_C", ".12x70 Led slug"},
        {"BP_12x70_Grizzly_Uam_C", ".12x70 Grizzly"},
        {"BP_12x70_BMG_Uam_C", ".12x70 BMG"},
        {"BP_12x70_AP20_Uam_C", ".12x70 AP20"},
        {"BP_12x70_Magnum_Uam_C", ".12x70 Magnum"},
        {"BP_12x70_525mm_Uam_C", ".12x70 5.25mm"},
        {"BP_12x70_Flechette_Uam_C", ".12x70 Flechette"},
        {"BP_12x70_Dual_Uam_C", ".12x70 Dual"},
        {"BP_762x51mm_M80_Uam_C", ".762x51mm M80"},
        {"BP_Caliber_762x51mm_Uam_C", "弹药口径 .762x51mm"},
        {"BP_762x51mm_M62_Uam_C", ".762x51mm M62"},
        {"BP_762x51mm_M61_Uam_C", ".762x51mm M61"},
        {"BP_762x51mm_UN_Uam_C", ".762x51mm UN"},
        {"BP_762x51mm_FMJ_Uam_C", ".762x51mm FMJ"},
        {"BP_762x51mm_Tutorial_Uam_C", ".762x51mm Tutorial"},
        {"BP_57x28mm_R37F_Uam_C", ".57x28mm R37F"},
        {"BP_57x28mm_SS197SR_Uam_C", ".57x28mm SS197SR"},
        {"BP_57x28mm_SS190_C", ".57x28mm SS190"},
        {"BP_57x28mm_R37X_Uam_C", ".57x28mm R37X"},
        {"BP_57x28mm_L191_Uam_C", ".57x28mm L191"},
        {"BP_57x28mm_SS198_Uam_C", ".57x28mm SS198"},
        {"BP_Caliber_9x39mm_Uam_C", ".9x39mm"},
        {"BP_9x39mm_7N9_Uam_C", ".9x39mm 7N9"},
        {"BP_545x39mm_HP_Uam_C", ".545x39mm HP"},
        {"BP_545x39mm_BP_Uam_C", ".545x39mm BP"},
        {"BP_545x39mm_BS_Uam_C", ".545x39mm BS"},
        {"BP_545x39mm_PP_Uam_C", ".545x39mm PP"},
        {"BP_545x39mm_PRS_C", ".545x39mm PRS"},
        {"BP_545x39mm_Tutorial_C", ".545x39mm Tutorial"},
        {"BP_127x99mm_NATO_C", ".127x99mm NATO"},
        {"BP_44_JSP_C", ".44 JSP"},
        {"BP_44_LFN_P_C", ".44 LFN P"},
        {"BP_44_LFN_GC_C", ".44 LFN GC"},
        {"BP_44_JHP_C", ".44 JHP"},
        {"BP_44_SJHP_C", ".44 SJHP"},
        {"BP_45_ACP_AP_C", ".45 ACP AP"},
        {"BP_45_ACP_FMJ_C", ".45 ACP FMJ"},
        {"BP_45_HS_C", ".45 HS"},
        {"BP_45_LM_C", ".45 LM"},
        {"BP_45_RIP_C", ".45 RIP"},
        {"BP_Caliber_762x25mm_C", ".762x25mm"},
        {"BP_762x25mm_TT_LRN_C", ".762x25mm TT LRN"},
        {"BP_762x25mm_TT_AKBS_C", ".762x25mm TT AKBS"},
        {"BP_762x25mm_TT_PST_C", ".762x25mm TT PST"},
        {"BP_762x25mm_TT_GZH_C", ".762x25mm TT GZH"},
        {"BP_338_AP_C", ".338 AP"},
        {"BP_338_FMJ_C", ".338 FMJ"},
        {"BP_338_TACX_C", ".338 TACX"},
        {"BP_338_UPZ_C", ".338 UPZ"},
        {"BP_Caliber_Missile_Uam_C", "导弹口径"},
        {"BP_Missile_M67_Uam_C", "导弹 M67"},
        {"BP_Throwable_Projectile_M67_Missile_C", "可投掷物体 导弹 M67"},
        {"BP_Throwable_Projectile_M67_C", "可投掷物体 导弹 M67"},
        {"BP_DamageType_FragGrenade_M67_Uam_C", "伤害类型 爆炸榴弹 M67"},
        {"BP_DamageType_Explode_C", "伤害类型 爆炸"},
        {"BP_Missile_M18_Uam_C", "导弹 M18"},
        {"BP_Throwable_Projectile_M18_Missile_C", "可投掷物体 导弹 M18"},
        {"BP_Throwable_Projectile_M18_C", "可投掷物体 导弹 M18"},
        {"BP_Missile_Z3_Uam_C", "导弹 Z3"},
        {"BP_Throwable_Projectile_Zarya_Missile_C", "可投掷物体 导弹 Zarya"},
        {"BP_Throwable_Projectile_Zarya_C", "可投掷物体 导弹 Zarya"},
        {"BP_Missile_M84_Uam_C", "导弹 M84"},
        {"BP_Throwable_Projectile_M84_Missile_C", "可投掷物体 导弹 M84"},
        {"BP_Throwable_Projectile_M84_C", "可投掷物体 导弹 M84"},
        {"BP_Missile_PetrolBomb_Uam_C", "导弹 PetrolBomb"},
        {"BP_Throwable_Projectile_Molotov_Missile_C", "可投掷物体 导弹 Molotov"},
        {"BP_Throwable_Projectile_Molotov_C", "可投掷物体 导弹 Molotov"},
        {"BP_DamageType_PetrolBomb_Molotov_Uam_C", "伤害类型 PetrolBomb"},
        {"BP_Missile_X-5Device_Uam_C", "导弹 X-5Device"},
        {"BP_Throwable_Projectile_X-5Device_Missile_C", "可投掷物体 导弹 X-5Device"},
        {"BP_Throwable_Projectile_X-5Device_C", "可投掷物体 导弹 X-5Device"},
        {"BP_Missile_GLI-F4_Uam_C", "导弹 GLI-F4"},
        {"BP_Throwable_Projectile_Teargas_Missile_C", "可投掷物_催泪气体_导弹"},
        {"BP_Throwable_Projectile_Teargas_C", "可投掷物_催泪气体"},
        {"BP_Teargas_Uam_C", "催泪气体"},
        {"BP_Missile_GHO-2_Uam_C", "导弹_GHO-2"},
        {"BP_Throwable_Projectile_HEG_Missile_C", "可投掷物_高爆榴弹_导弹"},
        {"BP_Throwable_Projectile_HEG_C", "可投掷物_高爆榴弹"},
        {"BP_DamageType_OffensiveGrenade_HEG_Uam_C", "伤害类型_进攻榴弹_高爆"},
        {"BP_Missile_Z3BOSS_Uam_C", "导弹_Z3BOSS"},
        {"BP_Missile_Z3BOSS_Uam_C", "导弹_Z3BOSS"},
        {"BP_Throwable_Projectile_Zarya_BossonlyMissile_C", "可投掷物_Zarya专属导弹"},
        {"BP_Throwable_Projectile_ZaryaBossonly_C", "可投掷物_Zarya专属"},
        {"BP_UAPickUpBase_C", "可拾取物基类"},
        {"BP_MFClimateLightningChannel_C", "气候闪电通道"},
        {"BP_MFClimateSpriteCelestial_C", "气候精灵_天体"},
        {"BP_CloudMaskBaseWeatherMap_C", "云遮罩基类_天气地图"},
        {"BP_PickupTrucks01_C", "皮卡车01"},
        {"BP_SequenceBaseActor_C", "序列基类角色"},
        {"BP_Muzzle_D45ACP_Anarchy_C", "枪口装置_D45ACP_Anarchy"},
        {"BP_MuzzleBase_C", "枪口基类"},
        {"BP_OralLiquids1_C", "口服液剂1"},
        {"BP_RecoveryBase_C", "恢复基类"},
        {"BP_Muzzle_M3A1_Flashhider_C", "枪口装置_M3A1_消焰器"},
        {"BP_Pistolgrip_M1911_ALG423_C", "手枪握把_M1911_ALG423"},
        {"BP_Mag_762x39mmR_10R_SKS_Uam_C", "弹夹_762x39mmR_10发_SKS"},
        {"BP_Stock_SKS_Sb5_Uam_C", "枪托_SKS_Sb5"},
        {"BP_DamageType_SKS_Uam_C", "伤害类型_SKS"},
        {"BP_DMR_WeaponBase_C", "精确射手武器基类"},
        {"BP_Weapon_SKS_Uam_C", "武器_SKS"},
        {"BP_Magnet_C", "磁铁"},
        {"BP_Humpback_C", "座头鲸"},
        {"BP_IronSight_Rear_SKS_Uam_C", "游戏实例"},
        {"BP_Tube_C", "管子"},
        {"BP_GunpowderGreen_C", "火药绿茶"},
        {"BP_Laser_TBL_C", "激光_TBL"},
        {"BP_LaserBase_C", "激光基类"},
        {"BP_Herring_C", "鲱鱼"},
        {"BP_CMS2_C", "CMS2"},
        {"BP_LampES_C", "台灯_ES"},
        {"BP_GreenTea_C", "绿茶"},
        {"BP_PineappJc_C", "菠萝派"},
        {"BP_AntiRoach_C", "驱虫剂"},
        {"BP_Mag_45mm_15R_M3A1_C", "弹夹_45mm_15发_M3A1"},
        {"BP_Helix_C", "螺旋"},
        {"BP_MRE_C", "MRE即食餐"},
        {"BP_Alkali_C", "碱性物质"},
        {"BP_HandGuard_AKM_Wood_Uam_C", "手把_AKM_木质"},
        {"BP_Mag_762x25mm_8R_CZ52_C", "弹夹_762x25mm_8发_CZ52"},
        {"BP_H2O2_C", "过氧化氢"},
        {"BP_Helmet_UNTAR_C", "头盔_UNTAR"},
        {"BP_Water_C", "水"},
        {"BP_Mag_9x19mm_10R_Glock_C", "弹夹_9x19mm_10发_Glock"},
        {"BP_Pomjuice_C", "葡萄汁"},
        {"BP_Cola_C", "可乐"},
        {"BP_CharacterAnimationSets_Submachine_Uam_C", "角色动画集_冲锋枪"},
        {"BP_DamageType_MP5_Uam_C", "伤害类型_MP5"},
        {"BP_SMG_WeaponBase_C", "冲锋枪武器基类"},
        {"BP_Weapon_UZI_Uam_C", "武器_UZI"},
        {"BP_Stock_UZI_Regular_Uam_C", "枪托_UZI_标准"},
        {"BP_CameraShake_ADS_T05_C", "ADS_T05瞄准时相机震动"},
        {"BP_CameraShake_Ironsight_T05_C", "瞄准器_T05瞄准时相机震动"},
        {"BP_CameraShake_T05_C", "T05相机震动"},
        {"BP_CharacterAnimationSets_Pistol_Uam_C", "角色动画集_手枪"},
        {"BP_Pistol_WeaponBase_C", "手枪武器基类"},
        {"BP_Weapon_T05_C", "武器_T05"},
        {"BP_Croutons_C", "面包丁"},
        {"BP_GpowerB_C", "G能量饮料"},
        {"BP_DeliciousTushonka_C", "美味Tushonka罐头"},
        {"BP_Pliers_C", "钳子"},
        {"BP_Emelya_C", "Emelya"},
        {"BP_Realy_C", "弹簧"},
        {"BP_Stock_MAC10_Standard_C", "枪托_MAC10_标准"},
        {"BP_Saury_C", "秋刀鱼"},
        {"BP_Linen_C", "亚麻布"},
        {"BP_Helmet_TC2001_C", "头盔_TC2001"},
        {"BP_Barrel_MAC10_5d75in_C", "枪管_MAC10_5.75英寸"},
        {"BP_Barrel_Glock17_Standard_Uam_C", "枪管_Glock17_标准"},
        {"BP_Weapon_T54_C", "武器_T54"},
        {"BP_CameraShake_ADS_Glock17_Uam_C", "ADS_Glock17相机震动"},
        {"BP_CameraShake_Glock17_Uam_C", "Glock17相机震动"},
        {"BP_CameraShake_Ironsight_Glock17_Uam_C", "瞄准器_Glock17相机震动"},
        {"BP_DamageType_MAC10_C", "伤害类型_MAC10"},
        {"BP_Weapon_MAC10_C", "武器_MAC10"},
        {"BP_ReceiverCover_MAC10_Standard_C", "MAC10_标准"},
        {"BP_Bag_VestContainer_LBT1961A_C", "背心背包容器_LBT1961A"},
        {"BP_Bleach_C", "漂白剂"},
        {"BP_Nails_C", "钉子"},
        {"BP_Peas_C", "豌豆"},
        {"BP_NRGDrink_C", "能量饮料"},
        {"BP_Zibbo_C", "Zibbo"},
        {"BP_BatteryD_C", "D电池"},
        {"BP_Sprats_C", "沙丁鱼"},
        {"BP_Wiper_C", "雨刮器"},
        {"BP_GoldenStar_C", "金质星星"},
        {"BP_Mag_762x25mm_8R_T54_C", "弹夹_762x25mm_8发_T54"},
        {"BP_Barrel_MP133_610mm_Uam_C", "枪管_MP133_610mm"},
        {"BP_Saferope_C", "安全绳"},
        {"BP_Rectifier_C", "整流器"},
        {"BP_Brass_C", "黄铜"},
        {"BP_Car2_C", "汽车2"},
        {"BP_Mag_D45_15R_MAC10_C", "弹夹_D45_15发_MAC10"},
        {"BP_Vest_Multicam_C", "多迪克迷彩背心"},
        {"BP_VestBase_C", "背心基类"},
        {"BP_IronSight_Rear_M870_XSShort_Uam_C", "M870_XS短枪口瞄准器_后"},
        {"BP_Helmet_KiverM_C", "头盔_KiverM"},
        {"BP_408060036_C", "408060036"},
        {"BP_Milk_C", "牛奶"},
        {"BP_Mag_12x70_4R_M870_Uam_C", "弹夹_12x70mm_4发_M870"},
        {"BP_HandGuard_AKS74U_B11_C", "AKS74U_手把_B11"},
        {"BP_Barrel_M870_325mm_Uam_C", "枪管_M870_325mm"},
        {"BP_ScrewdriverF_C", "螺丝刀F"},
        {"BP_Capacitor_C", "电容器"},
        {"BP_Battery_C", "电池"},
        {"BP_Pistolgrip_SAW_AKM_Uam_C", "SAW_AKM手枪握把"},
        {"BP_TPlug_C", "T型插头"},
        {"BP_AI3_C", "AI3"},
        {"BP_ChestRigs_VestContainer_M1995_C", "M1995背心背包容器"},
        {"BP_HandGuard_MP133_Izhmesh_Uam_C", "MP133_Izhmesh手把"},
        {"BP_Stock_M870_SPS_Uam_C", "M870_SPS枪托"},
        {"BP_Stock_MP133_std_Uam_C", "MP133标准枪托"},
        {"BP_Screwdriver_C", "螺丝刀"},
        {"BP_GasTube_AKS74U_C", "AKS74U气管"},
        {"BP_ReceiverCover_AKS74U_6P26_C", "AKS74U枪机盖_6P26"},
        {"BP_Stock_AKS74_6P21_C", "AKS74_枪托_6P21"},
        {"BP_Weapon_AKS74U_C", "武器_AKS74U"},
        {"BP_plexiglas_C", "亚克力板"},
        {"BP_Pistolgrip_M1911_Standard_C", "M1911_标准手枪握把"},
        {"BP_CameraShake_ADS_M1911_C", "ADS_M1911瞄准时相机震动"},
        {"BP_CameraShake_Ironsight_M1911_C", "瞄准器_M1911瞄准时相机震动"},
        {"BP_CameraShake_M1911_C", "M1911相机震动"},
        {"BP_Weapon_M1911_C", "武器_M1911"},
        {"BP_Calender_C", "挂历"},
        {"BP_ReceiverCover_M1911_C", "M1911枪机盖"},
        {"BP_DamageType_M870_Uam_C", "伤害类型_M870"},
        {"BP_Weapon_M870_Uam_C", "武器_M870"},
        {"BP_HandGuard_M870_Speedfeed_Uam_C", "M870_Speedfeed手把"},
        {"BP_CMTape_C", "胶带"},
        {"BP_EnamelCup_C", "搪瓷杯"},
        {"BP_408060038_C", "408060038"},
        {"BP_IronSight_Rear_M1911_C", "M1911后瞄准器_后"},
        {"BP_Mag_44_8R_DesertEagle_C", "弹夹_44_8发_DesertEagle"},
        {"BP_IronSight_Front_M1911_C", "M1911前瞄准器_前"},
        {"BP_Barrel_M1911_Standard_C", "M1911_标准枪管"},
        {"BP_Muzzle_545x39mm_6P26_0-20_C", "枪口装置_545x39mm_6P26_0-20"},
        {"BP_Sodium_C", "钠"},
        {"BP_Bag_MyContainer_Duffle_C", "背包_我的容器_双肩包"},
        {"BP_Bandage_C", "绷带"},
        {"BP_Diarys_C", "日记本"},
        {"BP_Barrel_M870_508mm_Uam_C", "M870_枪管_508mm"},
        {"BP_GasBlock_AR15_PicBlock_Uam_C", "AR15_PicBlock气体阀"},
        {"BP_DamageType_M3A1_C", "伤害类型_M3A1"},
        {"BP_Weapon_M3A1_C", "武器_M3A1"},
        {"BP_Weapon_CZ52_C", "武器_CZ52"},
        {"BP_Barrel_M3A1_8in_C", "M3A1_8英寸枪管"},
        {"BP_Foregrip_RVG_Uam_C", "前握把_RVG"},
        {"BP_ForegripBase_C", "前握把基础"},
        {"BP_Stock_M3A1_Stantard_C", "M3A1_标准枪托"},
        {"BP_DamageType_SmokeGrenade_M18_Uam_C", "烟雾手雷_M18_伤害类型"},
        {"BP_FireMode_SmokeGrenade_M18_Uam_C", "烟雾手雷_M18_开火模式"},
        {"BP_ThrowWeaponBase_C", "投掷武器基础"},
        {"BP_Weapon_SmokeGrenade_M18_Uam_C", "武器_烟雾手雷_M18"},
        {"BP_Canteen_C", "水壶"},
        {"BP_Pliers_Round_C", "圆钳"},
        {"BP_408080022_C", "408080022"},
        {"BP_Condmilk_C", "牛奶罐"},
        {"BP_Crackers_C", "饼干"},
        {"BP_ReceiverCover_CZ52_C", "CZ52枪机盖"},
        {"BP_Vest_2M_C", "2M背心"},
        {"BP_Bag_VestContainer_MRig_C", "背包_背心容器_MRig"},
        {"BP_Flashlight_C", "手电筒"},
        {"BP_Mag_9x19mm_20R_UZI_Uam_C", "弹夹_9x19mm_20发_UZI"},
        {"BP_Tape_Blue_C", "蓝色胶带"},
        {"BP_Mag_D45ACP_7R_M1911_C", "弹夹_D45ACP_7发_M1911"},
        {"BP_Bolts_C", "螺栓"},
        {"BP_FireMode_FragGrenade_M67_Uam_C", "FragGrenade_M67_开火模式"},
        {"BP_Weapon_FragGrenade_M67_Uam_C", "武器_FragGrenade_M67"},
        {"BP_Mag_D45ACP_30R_MAC10_C", "弹夹_D45ACP_30发_MAC10"},
        {"BP_ScrewNut_C", "螺母"},
        {"BP_IronSight_Rear_Mosin_Uam_C", "莫辛_后瞄准器_后"},
        {"BP_IronSignt_Front_Mosin_Uam_C", "莫辛_前瞄准器_前"},
        {"BP_DamageType_Mosin_Uam_C", "莫辛_伤害类型"},
        {"BP_SnipeRifler_WeaponBase_C", "狙击步枪_武器基础"},
        {"BP_Weapon_Mosin_Uam_C", "武器_莫辛"},
        {"BP_Stock_Mosin_Rifle_C", "莫辛_枪托"},
        {"BP_Mag_762x54mmR_4R_Mosin_Uam_C", "弹夹_762x54mmR_4发_Mosin"},
        {"BP_Barrel_Mosin_730mm_Uam_C", "莫辛_枪管_730mm"},
        {"BP_Vest_6B232_C", "6B232背心"},
        {"BP_Mag_545x39mm_60R_6L31_Uam_C", "弹夹_545x39mm_60发_6L31"},
        {"BP_ArmyBandage_C", "军用绷带"},
        {"BP_Soap_C", "肥皂"},
        {"BP_DamageType_MP40_C", "MP40_伤害类型"},
        {"BP_Weapon_MP40_C", "武器_MP40"},
        {"BP_Bag_VestContainer_BankRobber_C", "背包_背心容器_抢劫犯"},
        {"BP_Rouble_C", "卢布"},
        {"BP_FireMode_PetrolBomb_Molotov_Uam_C", "汽油弹_Molotov_开火模式"},
        {"BP_Weapon_PetrolBomb_Molotov_Uam_C", "武器_Molotov_汽油弹"},
        {"BP_EyewearBase_C", "眼镜基础"},
        {"BP_FaceCoverBase_C", "面部遮挡基础"},
        {"BP_Hat_Boss_Renoir_C", "Renoir老板帽"},
        {"BP_HatBase_C", "帽子基础"},
        {"BP_CharacterAnimationSets_Pistol_Uam_Female", "手枪_角色动画集_Uam_女性"},
        {"BP_Grizzly3_C", "Grizzly3"},
        {"BP_Headsets_Razor_C", "Razor耳机"},
        {"BP_Notebooks_C", "笔记本电脑"},
        {"BP_MuzzleAdapter_WT0032-1_C", "枪口适配器_WT0032-1"},
        {"BP_RP_C", "RP"},
        {"BP_Pistolgrip_AR15_TD120001_Uam_C", "手枪握把_AR15_TD120001"},
        {"BP_PCB_C", "PCB"},
        {"BP_IronSight_Rear_TFX_Uam_C", "TT01_后瞄准器_后"},
        {"BP_VintageRadio_C", "复古收音机"},
        {"BP_Mag_556x45mm_10R_M96_C", "弹夹_556x45mm_10发_M96"},
        {"BP_Mayo_C", "蛋黄酱"},
        {"BP_Mag_762x39mm_10R_AKM_C", "弹夹_762x39mm_10发_AKM"},
        {"BP_Mag_556x45mm_30R_AR15_STANAG_Uam_C", "弹夹_556x45mm_30发_AR15_STANAG"},
        {"BP_Weapon_DesertEagle_C", "武器_DesertEagle"},
        {"BP_Mag_556x45mm_10R_PMAG_GEN3_Uam_C", "弹夹_556x45mm_10发_PMAG_GEN3"},
        {"BP_Salewa_C", "Salewa急救包"},
        {"BP_package_C", "包裹"},
        {"BP_QuestItemBase_C", "任务物品基础"},
        {"BP_Mount_M-lok_4d1in_Uam_C", "M-lok_4d1in挂载"},
        {"BP_MountBase_C", "挂载基础"},
        {"BP_IronSight_Rear_TT01_C", "TT01_后瞄准器_后"},
        {"BP_nutrient_C", "营养剂"},
        {"BP_Pistolgrip_CZ52_Standard_C", "CZ52_标准手枪握把"},
        {"BP_Mag_45_7R_M45A1_C", "弹夹_45_7发_M45A1"},
        {"BP_FD_C", "FD"},
        {"BP_Filter_C", "过滤器"},
        {"BP_Compass_C", "指南针"},
        {"BP_Barrel_MP133_510mm_Uam_C", "MP133_枪管_510mm"},
        {"BP_Reader_C", "阅读器"},
        {"BP_Surv12_C", "Surv12急救包"},
        {"BP_IronSight_Rear_TFX_Uam_C", "TFX_后瞄准器_后"},
        {"BP_Tool_C", "工具"},
        {"BP_Vest_M12_C", "M12背心"},
        {"BP_UAMobileGamePad_C", "移动游戏手柄"},
        {"BP_UAMobilePlayerInput_C", "移动玩家输入"},
        {"BP_G_MainSettingPanel_C", "G_主设置面板"},
        {"BP_G_GameBaseSettingPanel_C", "G_游戏基础设置面板"},
        {"BP_G_GameDLCSettingPanel_C", "G_游戏DLC设置面板"},
        {"BP_G_GameLanguagePanel_C", "G_游戏语言设置面板"},
        {"BP_G_GameOpretaPanel_C", "G_游戏操作设置面板"},
        {"BP_G_GameSensitivitySettingPanel_C", "G_游戏灵敏度设置面板"},
        {"BP_G_GameSoundSettingPanel_C", "G_游戏声音设置面板"},
        {"BP_G_GameVibrationPanel_C", "G_游戏振动设置面板"},
        {"BP_G_GameViewSettingPanel_C", "G_游戏视图设置面板"},
        {"BP_G_NetworkTestPanel_C", "G_网络测试面板"},
        {"BP_G_PrivacySettingPanel_C", "G_隐私设置面板"},
        {"BP_G_VideoSettingPanel_C", "G_视频设置面板"},
        {"BP_G_SwitchBtn_C", "G_切换按钮"},
        {"BP_G_SettingProgressBG_C", "G_设置进度背景"},
        {"BP_G_GameViewRecommend_C", "G_游戏视图推荐"},
        {"BP_G_GameViewTips_C", "G_游戏视图提示"},
        {"BP_G_NoClickable_C", "G_不可点击"},
        {"BP_G_SettingLensSensitivity_C", "G_设置镜头灵敏度"},
        {"BP_G_GameLangSoundSettingItem_C", "G_游戏语言音效设置项"},
        {"BP_G_GameLanguagePopupPanel_C", "G_游戏语言弹出面板"},
        {"BP_LangChooseItem_C", "选择语言项"},
        {"BP_G_PufferUI_C", "G_PufferUI"},
        {"BP_G_InletBtn_C", "G_入口按钮"},
        {"BP_G_SettingHeadTextBg_C", "G_设置头部文本背景"},
        {"BP_G_SettingProgress_C", "G_设置进度"},
        {"BP_G_SettingProgress_C", "G_设置进度背景"},
        {"BP_PufferPackageUI_C", "Puffer包装UI"},
        {"BP_SubmitItem_C", "提交物品"},
        {"BP_SubmitPopPanel_C", "提交弹出面板"},
        {"BP_MobileWidget_WatchLoading_C", "手表加载动画"},
        {"BP_HUDWidget_MetorTips_C", "能源提示"},
        {"BP_MobileWidget_Objective_C", "目标面板"},
        {"BP_MobileWidget_QuestReport_C", "任务报告面板"},
        {"BP_MobileWidget_TaskProgressBox_C", "任务进度框"},
        {"BP_MobileWidget_UrgentQuest_DangerBtn_C", "紧急任务_危险按钮"},
        {"BP_UamGameHUDTips_C", "Uam游戏HUD提示"},
        {"BP_MobileHUDWidget_EscapeCloseTime_C", "逃生关闭时间"},
        {"BP_MobileHUDWidget_EscapeStateItem_C", "逃生状态项"},
        {"BP_MobileHUDWidget_EscapeTimeInfo_C", "逃生时间信息"},
        {"BP_PCHUDWidget_ThrownDetect_C", "PCHUDWidget_投掷物检测"},
        {"BP_ThrownIndicator_C", "投掷指示器"},
        {"BP_PCHUDWidget_WeaponCrosshair_C", "PCHUDWidget_武器准星"},
        {"BP_MobileWidget_GamePadMainView_Effect_C", "主视图效果"},
        {"BP_SoundIndicator_HUD_C", "声音指示器"},
        {"BP_MobileWidget_Container_C", "物品容器"},
        {"BP_MobileWidget_NewBag_Container_C", "新背包容器"},
        {"BP_MobileWidget_TopMenuBar_C", "顶部菜单栏"},
        {"BP_HUDWidget_ActivityInventoryMark_C", "活动库存标记"},
        {"BP_MobileHUDWidegt_ValuablesTips_C", "贵重物品提示"},
        {"BP_HUDSubWidget_DossInfo_C", "Doss信息"},
        {"BP_HUDSubWidget_TeammateInfo_C", "队友信息"},
        {"BP_HUDWidget_TeammateInfo_C", "队友信息"},
        {"BP_IconScaleBoxPaddingComponent_C", "图标比例框填充组件"},
        {"BP_MobileWidget_DoorGateReport_C", "门门报告面板"},
        {"BP_MobileWidget_EvacuationPointAlarm_C", "撤离点警报"},
        {"BP_MobileWidget_FriendReservation_C", "好友预约"},
        {"BP_MobileWidget_TaskProgressItem_C", "任务进度项"},
        {"BP_MobileWidget_UrgentQuest_DangerInfo_C", "紧急任务_危险信息"},
        {"BP_MobileWidget_TopMenuBar_Item_C", "顶部菜单栏_项"},
        {"BP_MobileWidget_ContainerCharacterAndSet_C", "角色和套装容器"},
        {"BP_MobileWidget_Corpse_C", "尸体"},
        {"BP_MobileWidget_DragControllScrollBox_C", "拖拽控制滚动框"},
        {"BP_MobileWidget_DragShowItem_C", "拖拽显示物品"},
        {"BP_MobileWIdget_ExtraOperSubWindow_C", "额外操作子窗口"},
        {"BP_MobileWidget_LootContainer_C", "战利品容器"},
        {"BP_MobileWidget_NewInventoryItem_C", "新库存物品"},
        {"BP_MobileWidget_Role_C", "角色"},
        {"BP_MobileWidget_SelectMenu_C", "选择菜单"},
        {"BP_Widget_InfoWindowPanel_C", "信息窗口面板"},
        {"BP_MobileWidget_CheckMergeWindow_C", "检查合并窗口"},
        {"BP_MobileWidget_PickBag_Container_C", "拾取背包_容器"},
        {"BP_MobileWidget_SplitItemWindow_C", "分割物品窗口"},
        {"BP_MobileWidget_SelectMenu_Item_C", "选择菜单_项"},
        {"BP_MobileWidget_SelectMenu_ItemPopup_C", "选择菜单_项弹出"},
        {"BP_MobileWidget_SelectMenu_Level1Item_C", "选择菜单_一级项"},
        {"BP_MobileWidget_Buff_C", "增益提示"},
        {"BP_MobileWidget_ECG_C", "心电图"},
        {"BP_MobileWidget_PhysicalStrength_C", "体力"},
        {"BP_MobileWidget_StrengthBar_C", "体力条"},
        {"BP_InventoryItemNode_Assembling_C", "装配中物品节点"},
        {"BP_InventoryItemNode_DragHint_C", "拖动提示节点"},
        {"BP_InventoryItemNode_Search_C", "搜索节点"},
        {"BP_InventoryItemNode_SizePreview_C", "大小预览节点"},
        {"BP_InventoryItemNode_StateImageTop_C", "状态图像顶部节点"},
        {"BP_UseProgressBar_Bag_C", "使用进度条_背包"},
        {"BP_EquipItemNode_Assembling_C", "手持装备节点"},
        {"BP_EquipItemNode_LeftDownIcons_C", "左下图标节点"},
        {"BP_MobileHUDWidget_NewMapPanel_C", "NewMap面板"},
        {"BP_BigMap_DetailBoard_C", "大地图_详情面板"},
        {"BP_BigMap_MarkProduct_C", "大地图_标记产品"},
        {"BP_BigMap_TaskTitleItem_C", "大地图_任务标题项"},
        {"BP_BigMapCanvas_C", "大地图画布"},
        {"BP_PCHUDWidget_TabBtn_C", "PC HUD小部件_选项卡按钮"},
        {"BP_BigMap_TaskStyle_C", "大地图_任务风格"},
        {"BP_PCHUDWubwidget_Esapoints_C", "PC HUD小部件_选项卡按钮"},
        {"BP_PCHUDWubwidget_BlackMask_C", "玩家HUD小部件_黑色遮罩_C"},
        {"BP_MobileWidget_SeasonPannal_715_C", "移动端小部件_赛季面板_715_C"},
        {"BP_MobileWidget_Quest_QuestState_C", "移动端小部件_任务_任务状态_C"},
        {"BP_MobileWidget_Quest_TaskInfoPanel_C", "移动端小部件_任务_任务信息面板_C"},
        {"BP_MobileWidget_QuestTaskTargetItem_C", "移动端小部件_任务任务目标物品_C"},
        {"BP_MobileWidget_Quest_AffiliateInfo_C", "移动端小部件_任务_附属信息_C"},
        {"BP_MobileWidget_QuestRewardItem_C", "移动端小部件_任务_奖励物品_C"},
        {"BP_MobileWidget_Quest_TaskTargetItem_C", "移动端小部件_任务_任务目标物品_C"},
        {"BP_MobileWidget_QuestUnLockItem_C", "移动端小部件_任务_解锁物品_C"},
        {"BP_MobileWidget_Quest_TaskMark_C", "移动端小部件_任务_任务标记_C"},
        {"BP_MobileWidget_SeasonHideItem_C", "移动端小部件_赛季隐藏物品_C"},
        {"BP_MobileWidget_QuestMainPannal_C", "移动端小部件_任务主面板_C"},
        {"BP_MobileWidget_Quest_QuestState_715_C", "移动端小部件_任务_任务状态_715_C"},
        {"BP_MobileWidget_QuestMerchantInfo_C", "移动端小部件_任务_商人信息_C"},
        {"BP_MobileWidget_QuestTargetPannal_C", "移动端小部件_任务_目标面板_C"},
        {"BP_MobileWidget_QuestTaskInfoPanel_C", "移动端小部件_任务_任务信息面板_C"},
        {"BP_MobileWidget_QuestTaskListBtn_C", "移动端小部件_任务_任务列表按钮_C"},
        {"BP_MobileWidget_QuestTaskName_C", "移动端小部件_任务_任务名称_C"},
        {"BP_MobileWidget_QuestTargetItem_C", "移动端小部件_任务_任务目标物品_C"},
        {"BP_MobileWidget_Quest_PresetTabItem_715_C", "移动端小部件_任务_预设标签_715_C"},
        {"BP_MobileWidget_Health_C", "移动端小部件_生命值_C"},
        {"BP_InGame_HealthTab_C", "游戏内_生命值标签_C"},
        {"BP_MobileHUDLootPointToggleContent_C", "移动端HUD_战利品点切换内容_C"},
        {"BP_MobileHUDWidget_ClearSignButton_C", "移动端HUD_清除标记按钮_C"},
        {"BP_MobileHUDWidget_SelfSignButton_C", "移动端HUD_自我标记按钮_C"},
        {"BP_BigMap_TaskBtn_Check_C", "大地图_任务按钮_选中_C"},
        {"BP_MobileHUDWidget_QuestTraceButton_C", "移动端HUD_任务追踪按钮_C"},
        {"BP_MobileHUDEscapePointListItem_C", "移动端HUD_逃生点列表项_C"},
        {"BP_MobileHUDEscapeToggleContent_C", "移动端HUD_逃生点切换内容_C"},
        {"BP_MobileHUDSubWidget_EscapePointIcon_C", "移动端HUD_逃生点图标_C"},
        {"BP_ChaseActivityScanInterval_C", "追逐活动扫描间隔_C"},
        {"BP_PCHUDSubWidget_PlayerText_C", "玩家HUD子部件_玩家文本_C"},
        {"BP_PCHUDSubWidget_PlayerText_Switch_C", "玩家HUD子部件_玩家文本_切换_C"},
        {"BP_DoorBeUsedComponent_C", "门被使用组件_C"},
        {"BP_DoorMovmentComponent_C", "门移动组件_C"},
        {"BP_SGDoorBase_C", "SG门基类_C"},
        {"BP_WaterBase_C", "水体基类_C"},
        {"BP_ChargingHandle_AR15_Standard_Uam_C", "AR15标准充能柄_C"},
        {"BP_Mag_762x25mm_20R_T79_C", "762x25mm 20发弹匣_T79_C"},
        {"BP_MobileHUDSubWidget_MapSign_C", "移动端HUD子部件_地图标记_C"},
        {"BP_MobileHUDSubWidget_TeamPlayerIcon_C", "移动端HUD子部件_队友玩家图标_C"},
        {"BP_PCHUDSubWidget_MapPlayerIconBlack_C", "玩家HUD子部件_地图玩家图标_黑色_C"},
        {"BP_BigmapNameText_C", "大地图名称文本_C"},
        {"BP_PCHUDSubWidget_BigmapTest_C", "玩家HUD子部件_大地图测试_C"},
        {"BP_MobileHUDNormalQuestMark_C", "移动端HUD普通任务标记_C"},
        {"BP_AdTape_C", "广告磁带_C"},
        {"BP_PCHUDSubWidget_BigmapDangerArea_C", "玩家HUD子部件_大地图危险区域_C"},
        {"BP_Mag_762x25_20R_QC61_C", "762x25mm 20发弹匣_QC61_C"},
        {"BP_ReceiverCover_M4A1_Uam_C", "M4A1上机匣盖_C"},
        {"BP_DamageType_M4A1_Uam_C", "伤害类型_M4A1_C"},
        {"BP_Weapon_M4A1_Uam_C", "武器_M4A1_C"},
        {"BP_Sight_Scope_4x_HAMR_Uam_C", "瞄准镜_4x HAMR_C"},
        {"BP_Barrel_AR15_406mm_Uam_C", "枪管_AR15_406mm_C"},
        {"BP_XK_C", "XK_C"},
        {"BP_Oatflakes_C", "燕麦片_C"},
        {"BP_Sight_ReflexSight_DP_Uam_C", "瞄准镜_反射式瞄准镜_DP_C"},
        {"BP_Mag_556x45mm_60R_AR15_STANAG_Uam_C", "556x45mm 60发弹匣_AR15 STANAG_C"},
        {"BP_HotRod_C", "热杆车_C"},
        {"BP_BeardOil_C", "胡须油_C"},
        {"BP_Bag_VestContainer_Thunderbolt_C", "背包_背心容器_雷霆_C"},
        {"BP_Mag_45_20R_MPF45_C", "45口径 20发弹匣_MPF45_C"},
        {"BP_Badge_C", "徽章_C"},
        {"BP_DamageType_FAL_Uam_C", "伤害类型_FAL_C"},
        {"BP_Weapon_SA85_C", "武器_SA85_C"},
        {"BP_Muzzle_762x39mm_6P1_0-14_AKM_Uam_C", "枪口装置_762x39mm_6P1_0-14_AKM_C"},
        {"BP_HandGuard_AR15_MOEmid_Uam_C", "护手_AR15_MOE中段_C"},
        {"BP_408150001_C", "408.15.0001_C"},
        {"BP_Muzzle_556x45mm_Claymore_C", "枪口装置_556x45mm_克莱莫尔_C"},
        {"BP_Stamps_C", "邮票_C"},
        {"BP_Chr_M01_Mask_S10_C", "角色_M01_面具_S10_C"},
        {"BP_GasMaskBase_C", "防毒面具基类_C"},
        {"BP_StockPad_AR_RBP_Uam_C", "枪托垫_AR_RBP_C"},
        {"BP_StockBufferTube_Colt_Uam_C", "枪托缓冲管_Colt_C"},
        {"BP_Helmet_FastMT_C", "头盔_FastMT_C"},
        {"BP_Slickers_C", "雨衣_C"},
        {"BP_Vitajuice_C", "维他命果汁_C"},
        {"BP_Squash_C", "南瓜_C"},
        {"BP_Helmet_Tankhelmet_C", "头盔_坦克头盔_C"},
        {"BP_Stock_MOE_Uam_C", "枪托_MOE_C"},
        {"BP_Mag_45_25R_UMP_C", "45口径 25发弹匣_UMP_C"},
        {"BP_Mat_C", "垫子_C"},
        {"BP_Pager_C", "寻呼机_C"},
        {"BP_Helmet_Hat_Begadi_Fred_C", "头盔_贝加迪_Fred_C"},
        {"BP_Mag_12x70_5R_Sb5_C", "12x70mm 5发弹匣_Sb5_C"},
        {"BP_PhoneBroken_C", "损坏的手机_C"},
        {"BP_Stock_MPF45_Cap_C", "枪托_MPF45_Cap_C"},
        {"BP_Walkman_C", "随身听_C"},
        {"BP_MFilter_C", "M过滤器_C"},
        {"BP_Powercord_C", "电源线_C"},
        {"BP_Sugar_C", "糖_C"},
        {"BP_Salewa2_C", "Salewa急救包_C"},
        {"BP_Nippers_C", "钳子_C"},
        {"BP_WaterBottle_C", "水瓶_C"},
        {"BP_Meds_C", "药物_C"},
        {"BP_FireMode_FlashBang_M84_Uam_C", "火焰模式_闪光弹_M84_C"},
        {"BP_Weapon_FlashBang_M84_Uam_C", "武器_闪光弹_M84_C"},
        {"BP_MuzzleAdapter_DT_Uam_C", "枪口适配器_DT_C"},
        {"BP_Mount_M1911_NCStar_C", "枪械配件_ M1911_NCStar_C"},
        {"BP_Antenna_C", "天线_C"},
        {"BP_OralLiquids2_C", "口服液体_C"},
        {"BP_LampUV_C", "紫外灯_C"},
        {"BP_Steel_C", "钢材_C"},
        {"BP_DVDD_C", "DVD盘_C"},
        {"BP_Legs_03_C", "裤子_03_C"},
        {"BP_Laser_Perst3_C", "激光器_Perst3_C"},
        {"BP_Bartercoin_C", "交换币_C"},
        {"BP_eTGc_C", "电子烟_C"},
        {"BP_Helmet_SHPM_C", "头盔_SHPM_C"},
        {"BP_Gloves_03_C", "手套_03_C"},
        {"BP_Mag_12x70_7R_M870_Uam_C", "12x70mm 7发弹匣_M870_C"},
        {"BP_Coffee_C", "咖啡_C"},
        {"BP_JBD_C", "JBD_C"},
        {"BP_Zagustin_C", "Zagustin_C"},
        {"BP_Poker_C", "扑克牌_C"},
        {"BP_AplJc_C", "AplJc_C"},
        {"BP_Paper_C", "纸张_C"},
        {"BP_FireMode_X-5Device_C", "火焰模式_X-5装置_C"},
        {"BP_Weapon_FootstepDevice_X-5Device_C", "武器_脚步声装置_X-5装置_C"},
        {"BP_ChipG_C", "芯片G_C"},
        {"BP_Mag_9x19mm_17R_M9A3_Uam_C", "9x19mm 17发弹匣_M9A3_C"},
        {"BP_Tushonka_C", "酸奶_C"},
        {"BP_Foregrip_USAF_C", "前握把_USAF_C"},
        {"BP_FireMode_OffensiveGrenade_HEG_Uam_C", "火焰模式_进攻手榴弹_HEG_C"},
        {"BP_Weapon_OffensiveGrenade_HEG_Uam_C", "武器_进攻手榴弹_HEG_C"},
        {"BP_SightBase_RM33_Uam_C", "瞄准镜基座_RM33_C"},
        {"BP_Mount_Glock17_GBase_Uam_C", "枪械配件_Glock17_GBase_C"},
        {"BP_Thermometer_C", "温度计_C"},
        {"BP_Helmet_Hat_SSH40_C", "头盔_帽子_SSH40_C"},
        {"BP_Torso_03_C", "上衣_03_C"},
        {"BP_PhoneNew_C", "新手机_C"},
        {"BP_Key_VillageHouse_C", "钥匙_村舍_C"},
        {"BP_Mag_556x45mm_10R_Mini14_C", "556x45mm 10发弹匣_Mini14_C"},
        {"BP_IronSight_Rear_Glock_SE_Uam_C", "Glock_SE_Uam后瞄具"},
        {"BP_Mount_MPF45_Downrail_C", "MPF45下导轨_C"},
        {"BP_Muzzle_762x25mm_T85_C", "762x25mm T85枪口装置_C"},
        {"BP_Barrel_QC61_Mid_C", "QC61中段枪管_C"},
        {"BP_Pistolgrip_M9A3_Polymer_Uam_C", "M9A3聚合物手枪握把_Uam_C"},
        {"BP_Mag_9x19mm_10R_M9A3_C", "9x19mm 10发弹匣_M9A3_C"},
        {"BP_Drill_C", "钻头_C"},
        {"BP_DamageType_UMP45_C", "UMP45伤害类型_C"},
        {"BP_Weapon_UMP45_C", "UMP45武器_C"},
        {"BP_Weapon_M9A3_Uam_C", "M9A3武器_Uam_C"},
        {"BP_Key_A207_C", "A207钥匙_C"},
        {"BP_Mag_9x19mm_30R_MP5_Uam_C", "9x19mm 30发弹匣_MP5_Uam_C"},
        {"BP_Stock_QC61_Stantard_C", "QC61标准枪托_C"},
        {"BP_Helmet_UamastMT_C", "UamastMT头盔_C"},
        {"BP_Weapon_M45A1_Uam_C", "M45A1武器_Uam_C"},
        {"BP_Stock_UMP_C", "UMP枪托_C"},
        {"BP_Mount_UMP_Bott_C", "UMP底部挂件_C"},
        {"BP_PocketWatch_C", "怀表_C"},
        {"BP_AssultCarbine_WeaponBase_C", "突击卡宾枪_武器基类_C"},
        {"BP_DamageType_M96_Uam_C", "M96伤害类型_Uam_C"},
        {"BP_Weapon_M96_C", "M96武器_C"},
        {"BP_Bag_MyContainer_ArmyBag_C", "我的容器_军用包_C"},
        {"BP_Headsets_ComTac2_C", "头戴式耳机_ComTac2_C"},
        {"BP_Shoes_03_C", "鞋子_03_C"},
        {"BP_Pistolgrip_M45A1_Standard_C", "M45A1标准手枪握把_C"},
        {"BP_FuelTankM_C", "燃料箱_M_C"},
        {"BP_408060033_C", "408.06.0033_C"},
        {"BP_ReceiverCover_M45A1_C", "M45A1上机匣盖_C"},
        {"BP_Shampoo_C", "洗发水_C"},
        {"BP_ReceiverCover_M9A3_Slide_Uam_C", "M9A3上机匣盖_滑块_Uam_C"},
        {"BP_Nebulizer_C", "雾化器_C"},
        {"BP_Pistolgrip_QC61_Standard_C", "QC61标准手枪握把_C"},
        {"BP_Spark_C", "火花_C"},
        {"BP_ChainSilver_C", "银链_C"},
        {"BP_Barrel_UMP_8in_C", "UMP 8英寸枪管_C"},
        {"BP_DamageType_QC61_Uam_C", "QC61伤害类型_Uam_C"},
        {"BP_Weapon_QC61_Uam_C", "QC61武器_Uam_C"},
        {"BP_ReceiverCover_QC61_Standard_C", "QC61标准上机匣盖_C"},
        {"BP_Mount_MP5_MFIHKMOUNT_C", "MP5_MFIHKMOUNT挂件_C"},
        {"BP_Barrel_M9A3_Threaded_Uam_C", "M9A3螺纹枪管_Uam_C"},
        {"BP_Mag_45_15R_UMP_C", "45口径 15发弹匣_UMP_C"},
        {"BP_Vest_SN_42_C", "背心_SN_42_C"},
        {"BP_Rangfinder_C", "测距仪_C"},
        {"BP_408020022_C", "408.02.0022_C"},
        {"BP_Polyacetal_C", "聚酯醛_C"},
        {"BP_IronSight_Front_Glock_SE_Uam_C", "Glock_SE_Uam前瞄具"},
        {"BP_IronSight_Rear_M9A3_Uam_C", "M9A3_Uam后瞄具"},
        {"BP_IronSight_Front_QC61_C", "QC61前瞄具_C"},
        {"BP_CMS_C", "CMS_C"},
        {"BP_PUBandage_C", "公共卫生绷带_C"},
        {"BP_Mount_MP5_BT3X_C", "MP5_BT3X挂件_C"},
        {"BP_Fiber_C", "纤维_C"},
        {"BP_IronSight_Front_M9A3_Uam_C", "M9A3_Uam前瞄具"},
        {"BP_Vest_Module3M_C", "模块化背心3M_C"},
        {"BP_Stock_MPF45_Wood_C", "MPF45_木质枪托_C"},
        {"BP_Mag_45_30R_M3A1_C", "45口径 30发弹匣_M3A1_C"},
        {"BP_IronSight_Rear_QC61_C", "QC61后瞄具_C"},
        {"BP_Mag_9x19mm_30R_Vector_C", "9x19mm 30发弹匣_Vector_C"},
        {"BP_Cloth_C", "布料_C"},
        {"BP_LCDB_C", "液晶屏幕_双色屏_C"},
        {"BP_Paracord_C", "尼龙绳_C"},
        {"BP_Set_C", "套装_C"},
        {"BP_Pistolgrip_AR15_OMRG_AKM_Uam_C", "AR_SIG_Uam_AR15_OMRG手枪握把"},
        {"BP_SJ1TGLab_C", "SJ1TGLab_C"},
        {"BP_IronSight_Front_AR_SIG_Uam_C", "AR_SIG_Uam前瞄具"},
        {"BP_DamageType_MPF45_Uam_C", "MPF45伤害类型_Uam_C"},
        {"BP_Weapon_MPF45_Uam_C", "MPF45武器_Uam_C"},
        {"BP_Fcond_C", "Fcond_C"},
        {"BP_Key_C115_C", "C115钥匙_C"},
        {"BP_Stock_AK_ZenitPT1_Uam_C", "AK_ZenitPT1_Uam标准枪托_C"},
        {"BP_MYD_C", "MYD_C"},
        {"BP_IronSight_Rear_AR_SIGUam_C", "AR_SIG_Uam后瞄具"},
        {"BP_408020024_C", "408.02.0024_C"},
        {"BP_Powerbank_C", "移动电源_C"},
        {"BP_PropaneTank_C", "丙烷气瓶_C"},
        {"BP_GMCounter_C", "GM计数器_C"},
        {"BP_Sight_ReflexSight_EKP802_Uam_C", "瞄准镜_反射瞄准镜_EKP802_C"},
        {"BP_Ophthalmoscope_C", "眼底镜_C"},
        {"BP_GunpowderRed_C", "红色火药_C"},
        {"BP_Mount_M3A1_Sight_C", "M3A1瞄准镜挂件_C"},
        {"BP_Mag_D45ACP_11R_M1911_C", "45口径 ACP 11发弹匣_M1911_C"},
        {"BP_Mount_M1911_Weigand_C", "M1911_Weigand挂件_C"},
        {"BP_ReceiverCover_MPF45_Standard_C", "MPF45_标准上机匣盖_C"},
        {"BP_Mag_762x25mm_30R_T79_C", "762x25mm 30发弹匣_T79_C"},
        {"BP_Mount_Glock17_UM3_Uam_C", "Glock17_UM3_Uam挂件_C"},
        {"BP_Muzzle_JMAC_RRD-4C_C", "JMAC_RRD-4C枪口装置_C"},
        {"BP_Bag_MyContainer_Beta2_C", "我的容器_测试版2_C"},
        {"BP_Mount_Keymod_6in_Uam_C", "Keymod 6英寸挂件_Uam_C"},
        {"BP_SightBase_AC32062_Uam_C", "瞄准镜底座_AC32062_C"},
        {"BP_Mag_545x39mm_10R_AK100_Uam_C", "545x39mm 10发弹匣_AK100_Uam_C"},
        {"BP_Helmet_6B47_Clean_C", "6B47_Clean头盔_C"},
        {"BP_ReceiverCover_MPF45_Rail_C", "MPF45_Rail上机匣盖_C"},
        {"BP_Stock_M870_SGA_Uam_C", "M870_SGA_Uam标准枪托_C"},
        {"BP_Stock_MP5_EndCap_Uam_C", "MP5_EndCap_Uam枪托底座_C"},
        {"BP_Foregrip_RK0_Uam_C", "RK0_Uam前握把_C"},
        {"BP_SJ6TGLab_C", "SJ6TGLab_C"},
        {"BP_StockAdapter_UZI_Uam_C", "UZI_Uam枪托适配器_C"},
        {"BP_BOSS2_C", "BOSS2_C"},
        {"BP_Gloves_02_C", "手套_02_C"},
        {"BP_Mag_12x70_10R_SAI-02_C", "12x70mm 10发弹匣_SAI-02_C"},
        {"BP_Legs_02_C", "裤子_02_C"},
        {"BP_MCable_C", "MCable_C"},
        {"BP_Barrel_MP133_540mm_Uam_C", "MP133 540mm枪管_C"},
        {"BP_SightBase_AMM_Uam_C", "瞄准镜底座_AMM_C"},
        {"BP_Mag_762x25_30R_QC61_C", "762x25mm 30发弹匣_QC61_C"},
        {"BP_HandGuard_AKS74U_Wood_C", "AKS74U_木质护手_C"},
        {"BP_Muzzle_556x45mm_223CB_C", "556x45mm 223CB枪口装置_C"},
        {"BP_FoamY_C", "泡沫"},
        {"BP_Mount_T85_Standard_C", "T85_标准挂件_C"},
        {"BP_Helmet_Hat_MSA_C", "头盔_帽子_MSA"},
        {"BP_Mag_556x45mm_30R_AK100_Uam_C", "556x45mm 30发弹匣_AK100_Uam_C"},
        {"BP_Muzzle_9x19mm_4Port_Uam_C", "9x19mm 4孔枪口装置_Uam_C"},
        {"BP_Laser_ANPEQ15_C", "激光_ANPEQ15"},
        {"BP_Mount_UZI_Toprail_Uam_C", "UZI顶导轨挂件"},
        {"BP_Muzzle_762x25mm_T79_C", "762x25mm T79枪口装置"},
        {"BP_CPU_C", "中央处理器"},
        {"BP_Muzzle_762x39mm_DGNAK47B_C", "762x39mm DGNAK47B枪口装置"},
        {"BP_Controller_C", "控制器"},
        {"BP_HandGuard_T79_Basics_C", "T79基础护手"},
        {"BP_MuzzleAdapter_Mosin_thr_C", "Mosin枪口适配器"},
        {"BP_Mag_9x19mm_20R_MP5_C", "9x19mm 20发弹匣"},
        {"BP_Foregrip_VPG_Uam_C", "VPG前握把"},
        {"BP_HandGuard_T79_Modern_C", "T79现代护手"},
        {"BP_WeaponParts_C", "武器零件"},
        {"BP_Flashlight2_C", "手电筒2"},
        {"BP_Shoes_02_C", "鞋子_02"},
        {"BP_ScopeRing_30mm_Uam_C", "30mm瞄准环"},
        {"BP_408050028_C", "408.05.0028"},
        {"BP_Mount_Mosin_Kochetov_Uam_C", "Mosin底座挂件"},
        {"BP_ChargingHandle_AR15_BOTL_C", "AR15后拉柄"},
        {"BP_Jammer_C", "干扰器"},
        {"BP_ChargingHandle_AR15_RapotrCharge_C", "AR15拉柄"},
        {"BP_Weapon_Vector9_Uam_C", "Vector9武器"},
        {"BP_Fan_C", "风扇"},
        {"BP_Muzzle_762x39mm_DTK-1_C", "762x39mm DTK-1枪口装置"},
        {"BP_Torso_02_C", "上衣_02"},
        {"BP_ReceiverCover_SOK_Sb02_C", "SOK Sb02上机匣盖"},
        {"BP_Muzzle_D45ACP_MPF45_Flashhider_C", "D45ACP_MPF45消焰器枪口装置"},
        {"BP_Muzzle_762x25_QC61_Flashhider_C", "762x25_QC61消焰器枪口装置"},
        {"BP_Sight_ReflexSight_RMR_Uam_C", "反射瞄准镜_RMR"},
        {"BP_Mag_45_30R_MPF45_C", "45口径 30发弹匣_MPF45"},
        {"BP_Barrel_Vector_5in_9x19mm_C", "9x19mm 5英寸枪管_Vector"},
        {"BP_TwoWayRadio_C", "双向收发无线电"},
        {"BP_Pistolgrip_AR15_A2_AKM_Uam_C", "AR15_A2_AKM_Uam手枪握把"},
        {"BP_Toolbag_C", "工具包"},
        {"BP_BatteryR_C", "电池R"},
        {"BP_Muzzle_12x70mm_GK02_C", "12x70mm GK02枪口装置"},
        {"BP_ScopeRing_SKSDP_Uam_C", "SKSDP瞄准镜底座"},
        {"BP_Mag_762x39mm_30R_AKM_Uam_C", "762x39mm 30发弹匣_AKM_Uam"},
        {"BP_ScopeRing_DPCSM_Uam_C", "DPCSM瞄准镜底座"},
        {"BP_Weapon_Saiga12_C", "Saiga12武器"},
        {"BP_Mount_M-lok_2d5in_Uam_C", "M-lok 2.5英寸挂件"},
        {"BP_Helmet_Kolpak_C", "Kolpak头盔"},
        {"BP_Headsets_Sordin_C", "Sordin耳机"},
        {"BP_Stock_T79_C", "T79枪托"},
        {"BP_Stock_QC61_Rail_C", "QC61导轨枪托"},
        {"BP_Pistolgrip_AK_RK3_Uam_C", "AK_RK3_Uam手枪握把"},
        {"BP_Stock_SOK_12AK_C", "SOK_12AK枪托"},
        {"BP_HandGuard_AK_TRAX1_C", "AK_TRAX1护手"},
        {"BP_FaceShieldBase_C", "面罩基座"},
        {"BP_Helmet_FShield_C", "面罩头盔"},
        {"BP_Penicillin_C", "青霉素"},
        {"BP_Foregrip_UVG_Uam_C", "UVG前握把"},
        {"BP_Foregrip_RK-1_Uam_C", "RK-1前握把"},
        {"BP_Gauge_C", "表"},
        {"BP_Key_Recycle_C", "回收钥匙"},
        {"BP_Mount_BM59_C", "BM59挂件"},
        {"BP_DamageType_FragGrenade_MKII_Uam_C", "Frag Grenade MKII伤害类型"},
        {"BP_FireMode_FragGrenade_MKII_Uam_C", "Frag Grenade MKII火力模式"},
        {"BP_Weapon_FragGrenade_MKII_Uam_C", "Frag Grenade MKII武器"},
        {"BP_Foregrip_BGVMK46K_Uam_C", "BGVMK46K前握把"},
        {"BP_Stock_UZI_Wooden_Uam_C", "UZI木质枪托"},
        {"BP_GGlasses_C", "太阳镜"},
        {"BP_Chr_M01_Mask_PMK_3_C", "M01面罩_PMK-3"},
        {"BP_SightBase_MPR45_Uam_C", "MPR45瞄准镜底座"},
        {"BP_SightBase_Compact_Uam_C", "紧凑瞄准镜底座"},
        {"BP_StockPad_AK_6G15U_Uam_C", "AK 6G15U软胶枪托垫"},
        {"BP_StockAdapter_MP133_12003_C", "MP133 12003枪托适配器"},
        {"BP_DamageType_T79_Uam_C", "T79伤害类型"},
        {"BP_Weapon_T79_C", "T79武器"},
        {"BP_Mount_M96_ATL_C", "M96瞄准镜底座"},
        {"BP_ScopeRing_34mm_NF_C", "34mm瞄准环"},
        {"BP_Pistolgrip_SA58_AGFAL_AKM_Uam_C", "SA58_AGFAL_AKM_Uam手枪握把"},
        {"BP_Muzzle_556x45mm_6p44_Uam_C", "556x45mm 6p44枪口装置"},
        {"BP_HandGuard_MP5_MP5WT_Uam_C", "MP5 MP5WT护手"},
        {"BP_HandGuard_SA58_Quadrail_Uam_C", "SA58四导轨护手"},
        {"BP_MuzzleAdapter_TR_C", "TR枪口适配器"},
        {"BP_MuzzleAdapter_TT_AKM_C", "TT_AKM枪口适配器"},
        {"BP_Mag_9x39mm_20R_VSS_Uam_C", "9x39mm 20发弹匣_VSS"},
        {"BP_Stock_Mosin_Std_Uam_C", "Mosin标准枪托"},
        {"BP_Stock_MP133_pistol_Uam_C", "MP133手枪枪托"},
        {"BP_Mag_556x45mm_30R_CWP_AK100_Uam_C", "556x45mm 30发弹匣_CWP_AK100"},
        {"BP_ScopeRing_Mosin_PU_Uam_C", "Mosin PU瞄准镜底座"},
        {"BP_HandGuard_SOK_Sb71_C", "SOK Sb71护手"},
        {"BP_Throwable_Projectile_MKII_C", "MKII投掷物"},
        {"BP_Mag_762x51mm_20R_M14_Uam_C", "762x51mm 20发弹匣_M14"},
        {"BP_Radio_C", "收音机"},
        {"BP_Mount_Mosin_MNG_C", "Mosin挂件"},
        {"BP_Weapon_AR30_Uam_C", "AR30武器"},
        {"BP_Weapon_Vector45_Uam_C", "Vector45武器"},
        {"BP_Mount_SVDS_DRGL1_Uam_C", "SVDS_DRGL1挂件"},
        {"BP_Muzzle_9x19mm_AAC_Illusion_9_C", "9x19mm AAC Illusion 9枪口装置"},
        {"BP_Mount_Mini14_TopRail_C", "Mini14顶导轨挂件"},
        {"BP_FireMode_StunGrenade_Zarya_Uam_C", "Zarya震荡手雷火力模式"},
        {"BP_Weapon_StunGrenade_Zarya_Uam_C", "Zarya震荡手雷武器"},
        {"BP_Mount_T79_C", "T79导轨挂件"},
        {"BP_Weapon_T85_C", "T85武器"},
        {"BP_Mount_AK102_B-13_Uam_C", "AK102 B-13挂件"},
        {"BP_DamageType_SmokeGrenade_Teargas_Uam_C", "烟雾手雷催泪煤伤害类型"},
        {"BP_FireMode_SmokeGrenade_Teargas_Uam_C", "烟雾手雷催泪煤火力模式"},
        {"BP_Weapon_SmokeGrenade_Teargas_Uam_C", "烟雾手雷催泪煤武器"},
        {"BP_Muzzle_762x39mm_PBS-1_C", "762x39mm PBS-1枪口装置"},
        {"BP_Mount_USAS12_Toprail_C", "USAS12顶导轨挂件"},
        {"BP_Shoes_07_C", "鞋子_07"},
        {"BP_Shoes_05_C", "鞋子_05"},
        {"BP_Mount_VSS_B3_combo_Uam_C", "VSS B3组合挂件"},
        {"BP_MuzzleAdapter_MP5_3lug_Uam_C", "MP5 3-lug枪口适配器"},
        {"BP_Muzzle_556x45mm_PWS_CQB_C", "556x45mm PWS CQB枪口装置"},
        {"BP_Head_02_C", "头部_02"},
        {"BP_Muzzle_762x39mm_RRD_4C_C", "762x39mm RRD-4C枪口装置"},
        {"BP_Torso_05_C", "上衣_05"},
        {"BP_Torso_07_C", "上衣_07"},
        {"BP_PhoneGolden_C", "金色手机"},
        {"BP_408120017_C", "408.12.0017"},
        {"BP_SightBase_RM35_Uam_C", "RM35瞄准镜底座"},
        {"BP_Camera_C", "相机"},
        {"BP_Muzzle_762x51mm_Atlas-7_C", "762x51mm Atlas-7枪口装置"},
        {"BP_Mount_Mosin_Patriot_Uam_C", "Mosin Patriot挂件"},
        {"BP_Head_05_C", "头部_05"},
        {"BP_Mount_AKS74U_B18_C", "AKS74U B18挂件"},
        {"BP_Weapon_MP5_Uam_C", "MP5武器"},
        {"BP_Haircolor_13_C", "发色_13"},
        {"BP_Haircolor_11_C", "发色_11"},
        {"BP_Haircolor_09_C", "发色_09"},
        {"BP_Key_EscapeBoat_C", "逃生船钥匙"},
        {"BP_Mag_9x19mm_32R_MP9_Uam_C", "9x19mm 32发弹匣_MP9"},
        {"BP_Key_House_C", "别墅钥匙"},
        {"BP_Key_Armory_C", "军火库钥匙"},
        {"BP_Lunchbox_C", "午餐盒"},
        {"BP_Mag_762x54mmR_10R_Mosin_Uam_C", "762x54mmR 10发弹匣_Mosin"},
        {"BP_Stock_Mosin_SawnOff_Uam_C", "Mosin截短枪托"},
        {"BP_Mag_9x39mm_30R_VSS_Uam_C", "9x39mm 30发弹匣_VSS"},
        {"BP_Muzzle_12x70mm_Monster_C", "12x70mm Monster枪口装置"},
        {"BP_Key_BiNanSuo_C", "碧南锁钥匙"},
        {"BP_Key_VillaGarage_C", "别墅车库钥匙"},
        {"BP_Key_MaTou_C", "马头钥匙"},
        {"BP_Key_VillaOffice_C", "别墅办公室钥匙"},
        {"BP_Legs_05_C", "腿部_05"},
        {"BP_Sight_ReflexSight_T1_Uam_Uam_C", "T1瞄准镜底座"},
        {"BP_Stock_AR15_M7A1PDW_Uam_C", "AR15 M7A1 PDW枪托"},
        {"BP_Legs_07_C", "腿部_07"},
        {"BP_StockAdapter_AKS74_PTLock_C", "AKS74 PTLock枪托适配器"},
        {"BP_StockPad_AR30_Rubber_C", "AR30橡胶枪托垫"},
        {"BP_StockAdapter_M870_LEO_C", "M870 LEO枪托适配器"},
        {"BP_Vest_6B2_C", "6B2防弹背心"},
        {"BP_Chr_M01_Mask_M50_C", "M01口罩_M50"},
        {"BP_Vest_6B23_C", "6B23防弹背心"},
        {"BP_SecureContainer_JiaxingContainer_C", "嘉兴集装箱"},
        {"BP_Mag_556x45mm_20R_Mini14_C", "556x45mm 20发弹匣_Mini14"},
        {"BP_IronSight_Rear_T85_C", "T85后瞄具"},
        {"BP_Mag_9x19mm_41R_MPX_C", "9x19mm 41发弹匣_MPX"},
        {"BP_IronSight_Front_T85_C", "T85前瞄具"},
        {"BP_FuelTank_C", "燃油箱"},
        {"BP_Stock_MP5_HKA2_Uam_C", "MP5 HKA2枪托"},
        {"BP_Stock_Mosin_PRS_Uam_C", "Mosin PRS枪托"},
        {"BP_Stock_AK_6P20SB7_Uam_C", "AK 6P20SB7软胶枪托"},
        {"BP_Mag_762x51_5R_Hunter_Uam_C", "762x51 5发弹匣_Hunter"},
        {"BP_Mag_762x54mm_10R_SVDS_Uam_C", "762x54mm 10发弹匣_SVDS"},
        {"BP_Stock_MAC10_Tactical_C", "MAC-10战术枪托"},
        {"BP_ChestRigs_VestContainer_PACA_C", "PACA防弹背心"},
        {"BP_Mag_762x51mm_20R_SA58_Uam_C", "762x51mm 20发弹匣_SA58"},
        {"BP_Helmet_Djeta_C", "Djeta头盔"},
        {"BP_Adrenaline_C", "肾上腺素"},
        {"BP_Stock_MPF45_Metal_C", "MPF45金属枪托"},
        {"BP_Headsets_Gssh01_C", "Gssh01耳机"},
        {"BP_Mag_12x70_20R_Powermag_C", "12x70mm 20发弹匣_Powermag"},
        {"BP_Helmet_SSh68_C", "SSh-68头盔"},
        {"BP_StockPad_AR30_Cheek_C", "AR30面颊枪托垫"},
        {"BP_TeargasNebulizer_C", "催泪煤雾化器"},
        {"BP_Pistolgrip_AR15_BattleGrip_C", "AR15 BattleGrip枪托"},
        {"BP_Pistolgrip_M870_AGR870_C", "M870 AGR870枪托"},
        {"BP_Helmet_KiverFS_C", "Kiver FS头盔"},
        {"BP_Mag_D45ACP_30R_Vector_C", "D45ACP 30发弹匣_Vector"},
        {"BP_Stock_T85_C", "T85枪托"},
        {"BP_Protection_LSHZ_2DT_C", "LSHZ-2DT防弹面罩"},
        {"BP_Stock_AR30_Stantard_C", "AR30标准枪托"},
        {"BP_Vest_3M_C", "3M防弹背心"},
        {"BP_VideoGame_C", "视频游戏"},
        {"BP_408060035_C", "408.06.0035"},
        {"BP_Mag_338_5R_AR30_C", "338 5发弹匣_AR30"},
        {"BP_Pistolgrip_AR15_StarkAR_C", "AR15 Stark AR握把"},
        {"BP_Sight_Holographic_HHS1_Uam_C", "Holographic HHS1瞄准镜底座"},
        {"BP_Pistolgrip_AR15_MIAD_C", "AR15 MIAD握把"},
        {"BP_ReceiverCover_MP5_Uam_C", "MP5机匣盖"},
        {"BP_Mag_12x70_10R_USAS12_C", "12x70mm 10发弹匣_USAS12"},
        {"BP_Mag_762x25mm_30R_T85_C", "762x25mm 30发弹匣_T85"},
        {"BP_StockAdapter_T79_C", "T79枪托适配器"},
        {"BP_Mag_D45ACP_50R_Vector_C", "D45ACP 50发弹匣_Vector"},
        {"BP_Barrel_Mosin_514mm_Uam_C", "Mosin 514mm枪管"},
        {"BP_Sight_ReflexSight_okp7_Uam_C", "OKP-7瞄准镜底座"},
        {"BP_408050029_C", "408050029"},
        {"BP_408050027_C", "408050027"},
        {"BP_ChargingHandle_MP5_Uam_C", "MP5上拉柄"},
        {"BP_ChargingHandle_MPX_Double_Uam_C", "MPX双上拉柄"},
        {"BP_SSD_C", "SSD"},
        {"BP_PSU_C", "PSU"},
        {"BP_ChargingHandle_AR15_Extended_C", "AR15扩展上拉柄"},
        {"BP_SASD_C", "SASD"},
        {"BP_Mag_20R_762x51mm_KAC_SR25_C", "20发762x51mm KAC SR25弹匣"},
        {"BP_Polystyrene_C", "聚苯乙烯"},
        {"BP_Mag_10R_762x51mm_KAC_SR25_C", "10发762x51mm KAC SR25弹匣"},
        {"BP_Virtex_C", "Virtex"},
        {"BP_Watch_C", "手表"},
        {"BP_Pistolgrip_AK_KGB_Uam_C", "AK KGB握把"},
        {"BP_HandGuard_AK_ZhukovU_C", "AK ZhukovU护手"},
        {"BP_Pistolgrip_SAW_FDE_C", "SAW FDE握把"},
        {"BP_Pistolgrip_AR15_HG15_C", "AR15 HG15握把"},
        {"BP_HandGuard_SOK_MTU002S_C", "SOK MTU002S护手"},
        {"BP_Barrel_SA58_11in_Uam_C", "SA58 11英寸枪管"},
        {"BP_Sight_Scope_1x4x_DR_Uam_C", "1x4x DR瞄准镜"},
        {"BP_Sight_Riflescope_3d5x_PU_Uam_C", "3.5x PU瞄准镜"},
        {"BP_Barrel_M1911_Threaded_C", "M1911螺纹枪管"},
        {"BP_Mag_44_8R_GoldDesertEagle_C", "44口径8发弹匣_黄金沙漠之鹰"},
        {"BP_Sight_Scope_4x_PSO1_Uam_C", "4x PSO-1瞄准镜"},
        {"BP_Barrel_T85_Standard_C", "T85标准枪管"},
        {"BP_Barrel_AR30_660mm_C", "AR30 660mm枪管"},
        {"BP_IronSight_Rear_MP5_Uam_C", "MP5后瞄具"},
        {"BP_GasBlock_AR15_MK12_Uam_C", "AR15 MK12气体块"},
        {"BP_Barrel_T85_Light_C", "T85轻枪管"},
        {"BP_RAM_C", "RAM"},
        {"BP_IronSight_Rear_F57_C", "F57后瞄具"},
        {"BP_IronSight_Front_F57_C", "F57前瞄具"},
        {"BP_ReceiverCover_FN57_C", "FN57机匣盖"},
        {"BP_Barrel_F57_Basics_C", "F57基础枪管"},
        {"BP_Mount_M14_Ultimak_Uam_C", "M14 Ultimak底座"},
        {"BP_Mag_556x45mm_100R_MAG5_C", "556x45mm 100发弹匣_MAG5"},
        {"BP_DamageType_F57_Uam_C", "F57伤害类型"},
        {"BP_Weapon_F57_Uam_C", "F57武器"},
        {"BP_Magazine_57x28_10R_F57_C", "5.7x28 10发弹匣_F57"},
        {"BP_DamageType_SPR310_Uam_C", "SPR310伤害类型"},
        {"BP_Weapon_SPR310_Uam_C", "SPR310武器"},
        {"BP_HandGuard_SPR310_C", "SPR310护手"},
        {"BP_Mag_762x39mm_50R_AKM_x47_C", "762x39mm 50发弹匣_AKM_x47"},
        {"BP_ReceiverCover_Glock17_Hex_C", "Glock17 Hex机匣盖"},
        {"BP_Muzzle_762x39mm_Rotor43_Uam_C", "762x39mm Rotor43枪口装置"},
        {"BP_Stock_Vector_Sling_Swivel_C", "Vector护肩吊环"},
        {"BP_HandGuard_AKS74U_GS_C", "AKS74U GS护手"},
        {"BP_Mount_MPF45_Uprail_C", "MPF45上导轨"},
        {"BP_Mag_762x51mm_5R_BM59_C", "762x51mm 5发弹匣_BM59"},
        {"BP_Mag_762x39mm_40R_AKM_Uam_C", "762x39mm 40发弹匣_AKM"},
        {"BP_IronSight_Rear_M4A1_CA2R_Uam_C", "M4A1 CA2R后瞄具"},
        {"BP_DamageType_SR25_C", "SR25伤害类型"},
        {"BP_Weapon_SR25_C", "SR25武器"},
        {"BP_ReceiverCover_SR25_C", "SR25机匣盖"},
        {"BP_Mag_20R_762x51mm_PMAG_SR25_C", "20发762x51mm PMAG SR25弹匣"},
        {"BP_MuzzleAdapter_KAC_QDC_C", "KAC QDC枪口适配器"},
        {"BP_HandGuard_SR25_URX_C", "SR25 URX护手"},
        {"BP_IronSight_Front_M4A1_KAC_Uam_C", "M4A1 KAC前瞄具"},
        {"BP_Stock_AR15_UBRGEN2_Uam_C", "AR15 UBR GEN2枪托"},
        {"BP_DamageType_Hunter_Uam_C", "猎人伤害类型"},
        {"BP_Weapon_Mini14_C", "Mini-14武器"},
        {"BP_Barrel_SR25_16in_C", "SR25 16英寸枪管"},
        {"BP_ChargingHandle_SR25_Ambi_C", "SR25双边上拉柄"},
        {"BP_Stock_Mini14_Wooden_C", "Mini-14木质枪托"},
        {"BP_Mag_762x51mm_30R_FAL_C", "762x51mm 30发弹匣_FAL"},
        {"BP_Mag_762x54R_5R_SVT_C", "762x54R 5发弹匣_SVT"},
        {"BP_Mag_9x39mm_10R_VSS_Uam_C", "9x39mm 10发弹匣_VSS"},
        {"BP_ReceiverCover_Glock17_Viper_C", "Glock17 Viper机匣盖"},
        {"BP_Mag_556x45mm_20R_PMAG_GEN3_Uam_C", "556x45mm 20发弹匣_PMAG GEN3"},
        {"BP_Mount_Long_Riser_Mount_C", "长底座"},
        {"BP_Mag_762x51_5R_M24_Uam_C", "762x51mm 5发弹匣_M24"},
        {"BP_Head_Female_04_C", "女性头部_04"},
        {"BP_Bag_MyContainer_6SH118_C", "6SH118背包"},
        {"BP_CharacterAnimationSets_EmptyHand_Uam_Female_C", "空手女性动画集"},
        {"BP_CharacterAnimationSets_Melee_Uam_Female_C", "近战武器女性动画集"},
        {"BP_PerWeaponAnimationSets_Uam_M9A3_C", "M9A3专属武器动画集"},
        {"BP_M9A3_AnimBp_Child_C", "M9A3动画BP_Child"},
        {"BP_Lens_C", "透镜"},
        {"BP_408060040_C", "408060040"},
        {"BP_CharacterAnimationSets_Submachine_Uam_Female_C", "冲锋枪女性动画集"},
        {"BP_PerWeaponAnimationSets_MP40_C", "MP40专属武器动画集"},
        {"BP_MP40_AnimBp_Child_C", "MP40动画BP_Child"},
        {"BP_M45A1_AnimBp_Child_C", "M45A1动画BP_Child"},
        {"BP_Chr_Npc16_Hair_Cap_01_C", "NPC16帽子头发"},
        {"BP_PerWeaponAnimationSets_T85_C", "T85专属武器动画集"},
        {"BP_T85_AnimBP_Child_C", "T85动画BP"},
        {"BP_T85_AnimBp_Child_C", "T85动画BP_Child"},
        {"BP_Helmet_6B47_C", "6B47头盔"},
        {"BP_PerWeaponAnimationSets_Uam_AKS74u_C", "AKS74u专属武器动画集"},
        {"BP_AKS74u_AnimBp_C", "AKS74u动画BP"},
        {"BP_CharacterAnimationSets_Submachine_Uam_Female_C", "Submachine女性动画集"},
        {"BP_PerWeaponAnimationSets_Uam_M870_C", "M870专属武器动画集"},
        {"BP_M870_AnimBP_Child_C", "M870动画BP_Child"},
        {"BP_AKM_AnimBp_Child_C", "AKM动画BP_Child"},
        {"BP_PerWeaponAnimationSets_Uam_AKs74n_C", "AKS74n专属武器动画集"},
        {"BP_AKs74n_AnimBp_Child_C", "AKs74n动画BP_Child"},
        {"BP_Dogtag55_C", "Dogtag55"},
        {"BP_PetrolBomb_Anim_BP_Child_C", "燃烧弹动画BP_Child"},
        {"BP_PerWeaponAnimationSets_Uam_PetrolBomb_C", "燃烧弹专属武器动画集"},
        {"Inventory_014NormalMediKit_C", "普通医疗包"},
        {"Inventory_017AdMediKit_C", "高级医疗包"},
        {"Inventory_008ToolBox_C", "工具箱"},
        {"Inventory_009AdToolBox_C", "高级工具箱"},
        {"Inventory_012SafeBox_C", "保险箱"},
        {"Inventory_015SportBag_C", "运动包"},
        {"Inventory_018LowMediKit_C", "低级医疗包"},
        {"Inventory_019AdCloth_C", "高级布料"},
        {"Inventory_011ElectronicSafe_C", "电子保险箱"},
        {"Inventory_002AdvanceWeaponCase_C", "高级武器箱"},
        {"Inventory_019AdCloth_02_C", "高级布料"},
        {"Inventory_010CashRegister_C", "收银机"},
        {"Inventory_006GrenadeBox_C", "手榴弹箱"},
        {"Inventory_001_BigWeaponCase_C", "大型武器箱"},
        {"Inventory_021LowCloth_02_C", "低级布料"},
        {"Inventory_021LowCloth_C", "低级布料"},
        {"Inventory_007AmmoBox_C", "弹药箱"},
        {"Inventory_005SquareWeaponBox_C", "方形武器箱"},
        {"Inventory_003LongWeaponCase_C", "长型武器箱"},
        {"Inventory_016Trunk_C", "后备箱"},
        {"Inventory_023OldPC_C", "旧电脑"},
        {"Inventory_020NormalCloth_C", "普通布料"},
        {"Inventory_013CabinetDrawer01_C", "柜子抽屉01"},
        {"Inventory_004WoodenWeaponCase_C", "木质武器箱"},
        {"Inventory_027BriefCase_C", "公文包"},
        {"Inventory_013CabinetDrawer02_C", "柜子抽屉02"},
        {"Inventory_CabinetDrawer_C", "柜子抽屉"},
        {"Inventory_013CabinetDrawer04_C", "柜子抽屉04"},
        {"Inventory_013CabinetDrawer03_C", "柜子抽屉03"},
        {"Inventory_035AmmoBox554x39_C", "5.45x39弹药箱"},
        {"Inventory_038AmmoBox9x19_C", "9x19mm弹药箱"},
};

std::string UamoGetString(string aid)
{
    if (UamoidMap.find(aid) != UamoidMap.end()) {
        return UamoidMap[aid];
    }
    return "未知";  // 或者返回一个默认名称
}
